import { msg } from '@lingui/core/macro';
import { DateDisplayFormat, FieldMetadataType } from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';

export const buildRetentionActionLogStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'retentionActionLog', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'retentionActionLog'>,
  FlatFieldMetadata
> => ({
  // System fields
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Custom fields
  actionType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'actionType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Action Type`),
      description: i18nLabel(msg`The retention action to perform`),
      icon: 'IconShield',
      isNullable: false,
      isUIEditable: true,
      options: [
        {
          id: 'b6886b19-bf6c-4765-94f2-ff13c1f659b5',
          value: 'DELETE',
          label: i18nLabel(msg`Delete`),
          position: 0,
          color: 'red',
        },
        {
          id: '827578cb-caf5-476f-9daf-63c0059c9385',
          value: 'RECTIFY',
          label: i18nLabel(msg`Rectify`),
          position: 1,
          color: 'orange',
        },
        {
          id: 'c78a5f22-26de-4632-80cd-f8aa4a02e517',
          value: 'RESTORE',
          label: i18nLabel(msg`Restore`),
          position: 2,
          color: 'green',
        },
        {
          id: '834e6b25-f22e-4121-b08e-4b880240c48d',
          value: 'LEGAL_HOLD',
          label: i18nLabel(msg`Legal Hold`),
          position: 3,
          color: 'purple',
        },
        {
          id: '089d6b4b-bcb1-4b06-ab6d-6f14f92176ea',
          value: 'LEGAL_HOLD_RELEASE',
          label: i18nLabel(msg`Legal Hold Release`),
          position: 4,
          color: 'blue',
        },
        {
          id: '16edef08-c41d-46fd-a6df-e75a348ecc17',
          value: 'PURGE',
          label: i18nLabel(msg`Purge`),
          position: 5,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  initiatorSystem: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'initiatorSystem',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Initiator System`),
      description: i18nLabel(msg`The system that initiated the action`),
      icon: 'IconServer',
      isNullable: false,
      isUIEditable: true,
      options: [
        {
          id: '9d456793-ee55-4cb9-a59a-a720d785a19b',
          value: 'TWENTY',
          label: i18nLabel(msg`Twenty`),
          position: 0,
          color: 'blue',
        },
        {
          id: '2cda84fa-85d6-408f-9d2a-03355862a6af',
          value: 'DIRECTUS',
          label: i18nLabel(msg`Directus`),
          position: 1,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetTwentyEntityName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'targetTwentyEntityName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Target Twenty Entity Name`),
      description: i18nLabel(msg`The Twenty object the action targets`),
      icon: 'IconTarget',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetTwentyRecordId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'targetTwentyRecordId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Target Twenty Record Id`),
      description: i18nLabel(msg`The Twenty record the action targets`),
      icon: 'IconTarget',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  externalSystemName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'externalSystemName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`External System Name`),
      description: i18nLabel(msg`The external system the action targets`),
      icon: 'IconServer',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  externalRecordId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'externalRecordId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`External Record Id`),
      description: i18nLabel(msg`The external record the action targets`),
      icon: 'IconServer',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  scope: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'scope',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Scope`),
      description: i18nLabel(msg`The scope of the retention action`),
      icon: 'IconScope',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  legalHoldReference: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'legalHoldReference',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Legal Hold Reference`),
      description: i18nLabel(msg`Reference for a legal hold action`),
      icon: 'IconScale',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Propagation status of the action`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'REQUESTED'",
      options: [
        {
          id: '69f5ed29-9d51-4aec-8823-ea3c3c831b95',
          value: 'REQUESTED',
          label: i18nLabel(msg`Requested`),
          position: 0,
          color: 'blue',
        },
        {
          id: '4ebb8078-bc65-4c8b-a54f-52077bcae7c2',
          value: 'PROPAGATED',
          label: i18nLabel(msg`Propagated`),
          position: 1,
          color: 'purple',
        },
        {
          id: '099258e1-3397-41e4-924b-2ea9f5669352',
          value: 'RECONCILED',
          label: i18nLabel(msg`Reconciled`),
          position: 2,
          color: 'green',
        },
        {
          id: '5ba859e3-7491-4152-87d5-30f7badb6062',
          value: 'FAILED',
          label: i18nLabel(msg`Failed`),
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  requestedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'requestedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Requested At`),
      description: i18nLabel(msg`When the action was requested`),
      icon: 'IconCalendarEvent',
      isNullable: false,
      isUIEditable: true,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  propagatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'propagatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Propagated At`),
      description: i18nLabel(msg`When the action was propagated`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  actorId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'actorId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Actor`),
      description: i18nLabel(msg`The workspace member who initiated the action`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceHash: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceHash',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source Hash`),
      description: i18nLabel(msg`Hash of the source payload for deduplication`),
      icon: 'IconHash',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Retention action log record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
