import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';

export const buildAiPromptTemplateStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'aiPromptTemplate', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'aiPromptTemplate'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`AI prompt template record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Prompt template name`),
      icon: 'IconMessage',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  description: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'description',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Description`),
      description: i18nLabel(msg`Prompt template description`),
      icon: 'IconNotes',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  promptText: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'promptText',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Prompt Text`),
      description: i18nLabel(msg`The prompt text sent to the model`),
      icon: 'IconTextSpellcheck',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  modelId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'modelId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Model`),
      description: i18nLabel(msg`Identifier of the model this prompt targets`),
      icon: 'IconRobot',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  responseFormat: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'responseFormat',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Response Format`),
      description: i18nLabel(msg`Expected response format from the model`),
      icon: 'IconBraces',
      isNullable: true,
      isUIEditable: true,
      defaultValue: "'TEXT'",
      options: [
        {
          id: 'c1a10030-0060-4000-8030-c1a100000501',
          value: 'TEXT',
          label: i18nLabel(msg`Text`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000502',
          value: 'JSON',
          label: i18nLabel(msg`Json`),
          position: 1,
          color: 'purple',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000503',
          value: 'STRUCTURED',
          label: i18nLabel(msg`Structured`),
          position: 2,
          color: 'teal',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  category: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'category',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Category`),
      description: i18nLabel(msg`Governance category of the prompt template`),
      icon: 'IconCategory',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'c1a10030-0060-4000-8030-c1a100000601',
          value: 'ASSIGNMENT_INTAKE',
          label: i18nLabel(msg`Assignment Intake`),
          position: 0,
          color: 'green',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000602',
          value: 'POSITION_SPEC',
          label: i18nLabel(msg`Position Spec`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000603',
          value: 'RESEARCH_STRATEGY',
          label: i18nLabel(msg`Research Strategy`),
          position: 2,
          color: 'teal',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000604',
          value: 'STATUS_REPORT',
          label: i18nLabel(msg`Status Report`),
          position: 3,
          color: 'purple',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000605',
          value: 'CANDIDATE_PRESENTATION',
          label: i18nLabel(msg`Candidate Presentation`),
          position: 4,
          color: 'orange',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000606',
          value: 'CRITERION_ASSESSMENT',
          label: i18nLabel(msg`Criterion Assessment`),
          position: 5,
          color: 'red',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000607',
          value: 'BOARD_MATRIX',
          label: i18nLabel(msg`Board Matrix`),
          position: 6,
          color: 'sky',
        },
        {
          id: 'c1a10030-0060-4000-8030-c1a100000608',
          value: 'SEARCH_HEALTH',
          label: i18nLabel(msg`Search Health`),
          position: 7,
          color: 'pink',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  version: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'version',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Version`),
      description: i18nLabel(msg`Version of the prompt template`),
      icon: 'IconVersions',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isActive: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isActive',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Active`),
      description: i18nLabel(msg`Whether this prompt template is active`),
      icon: 'IconCircleCheck',
      isNullable: false,
      isUIEditable: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isApproved: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isApproved',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Approved`),
      description: i18nLabel(msg`Whether this prompt template is approved`),
      icon: 'IconCheck',
      isNullable: false,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
