import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildSearchStatusReportStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'searchStatusReport', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'searchStatusReport'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Report name`),
      icon: 'IconUser',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reportType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reportType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Report Type`),
      description: i18nLabel(msg`Type of status report`),
      icon: 'IconCategory',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'WEEKLY'",
      options: [
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0008001',
          value: 'WEEKLY',
          label: i18nLabel(msg`Weekly`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0008002',
          value: 'BIWEEKLY',
          label: i18nLabel(msg`Biweekly`),
          position: 1,
          color: 'purple',
        },
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0008003',
          value: 'MONTHLY',
          label: i18nLabel(msg`Monthly`),
          position: 2,
          color: 'green',
        },
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0008004',
          value: 'QUARTERLY',
          label: i18nLabel(msg`Quarterly`),
          position: 3,
          color: 'orange',
        },
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0008005',
          value: 'AD_HOC',
          label: i18nLabel(msg`Ad Hoc`),
          position: 4,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Report status`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0009001',
          value: 'DRAFT',
          label: i18nLabel(msg`Draft`),
          position: 0,
          color: 'gray',
        },
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0009002',
          value: 'SUBMITTED',
          label: i18nLabel(msg`Submitted`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0009003',
          value: 'ACKNOWLEDGED',
          label: i18nLabel(msg`Acknowledged`),
          position: 2,
          color: 'green',
        },
        {
          id: 'aeb1a007-0060-4000-8007-aeb1a0009004',
          value: 'ARCHIVED',
          label: i18nLabel(msg`Archived`),
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reportDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reportDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Report Date`),
      description: i18nLabel(msg`Date of the report`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  periodStart: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'periodStart',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Period Start`),
      description: i18nLabel(msg`Start of the reporting period`),
      icon: 'IconCalendarPlus',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  periodEnd: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'periodEnd',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Period End`),
      description: i18nLabel(msg`End of the reporting period`),
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  activitiesSummary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'activitiesSummary',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Activities Summary`),
      description: i18nLabel(msg`Summary of activities performed`),
      icon: 'IconClipboardList',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidatePipelineSummary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'candidatePipelineSummary',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Candidate Pipeline Summary`),
      description: i18nLabel(msg`Summary of candidate pipeline status`),
      icon: 'IconUsers',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  nextSteps: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'nextSteps',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Next Steps`),
      description: i18nLabel(msg`Planned next steps`),
      icon: 'IconArrowRight',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  clientFeedbackRequested: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'clientFeedbackRequested',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Client Feedback Requested`),
      description: i18nLabel(msg`Whether client feedback was requested`),
      icon: 'IconMessage',
      isNullable: true,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  submittedBy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'submittedBy',
      label: i18nLabel(msg`Submitted By`),
      description: i18nLabel(msg`Who submitted the report`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'submittedReports',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'submittedById',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  submittedById: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'submittedById',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Submitted By ID`),
      description: i18nLabel(msg`Submitted by user ID`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  acknowledgedBy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'acknowledgedBy',
      label: i18nLabel(msg`Acknowledged By`),
      description: i18nLabel(msg`Who acknowledged the report`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'acknowledgedReports',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'acknowledgedById',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  acknowledgedById: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'acknowledgedById',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Acknowledged By ID`),
      description: i18nLabel(msg`Acknowledged by user ID`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignment: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'searchAssignment',
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchAssignment',
      targetFieldName: 'statusReports',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'searchAssignmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment ID`),
      description: i18nLabel(msg`Associated search assignment ID`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
