import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildConflictCheckStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'conflictCheck', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'conflictCheck'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(
        msg`Associated search assignment`,
      ),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectPerson: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'subjectPerson',
      label: i18nLabel(msg`Subject Person`),
      description: i18nLabel(msg`Person being checked for conflicts`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'person',
      targetFieldName: 'conflictCheckSubjectPersons',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'subjectPersonId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectCompany: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'subjectCompany',
      label: i18nLabel(msg`Subject Company`),
      description: i18nLabel(msg`Company being checked for conflicts`),
      icon: 'IconBuilding',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'company',
      targetFieldName: 'conflictCheckSubjectCompanies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'subjectCompanyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  matchedRestriction: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'matchedRestriction',
      label: i18nLabel(msg`Matched Restriction`),
      description: i18nLabel(msg`Off-limits restriction that matched`),
      icon: 'IconForbid2',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'offLimitsRestriction',
      targetFieldName: 'conflictChecks',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'matchedRestrictionId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  summary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'summary',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Summary`),
      description: i18nLabel(msg`Human-readable label for the conflict check`),
      icon: 'IconFileDescription',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'subjectType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Subject Type`),
      description: i18nLabel(msg`Whether the check targets a person or company`),
      icon: 'IconCategory',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'PERSON'",
      options: [
        {
          id: '84e9dfc7-0001-4000-8000-000000000001',
          value: 'PERSON',
          label: i18nLabel(msg`Person`),
          position: 0,
          color: 'blue',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000002',
          value: 'COMPANY',
          label: i18nLabel(msg`Company`),
          position: 1,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  checkType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'checkType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Check Type`),
      description: i18nLabel(msg`When the conflict check was triggered`),
      icon: 'IconShieldCheck',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'PRE_OUTREACH'",
      options: [
        {
          id: '84e9dfc7-0001-4000-8000-000000000010',
          value: 'PRE_OUTREACH',
          label: i18nLabel(msg`Pre-outreach`),
          position: 0,
          color: 'blue',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000011',
          value: 'PRE_PRESENTATION',
          label: i18nLabel(msg`Pre-presentation`),
          position: 1,
          color: 'turquoise',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000012',
          value: 'PRE_OFFER',
          label: i18nLabel(msg`Pre-offer`),
          position: 2,
          color: 'purple',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000013',
          value: 'CONTINUOUS',
          label: i18nLabel(msg`Continuous`),
          position: 3,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  outcome: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'outcome',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Outcome`),
      description: i18nLabel(msg`Result of the conflict check`),
      icon: 'IconCheck',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'CLEAR'",
      options: [
        {
          id: '84e9dfc7-0001-4000-8000-000000000020',
          value: 'CLEAR',
          label: i18nLabel(msg`Clear`),
          position: 0,
          color: 'green',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000021',
          value: 'REVIEW_REQUIRED',
          label: i18nLabel(msg`Review required`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000022',
          value: 'BLOCKED',
          label: i18nLabel(msg`Blocked`),
          position: 2,
          color: 'red',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000023',
          value: 'WAIVER_REQUIRED',
          label: i18nLabel(msg`Waiver required`),
          position: 3,
          color: 'orange',
        },
        {
          id: '84e9dfc7-0001-4000-8000-000000000024',
          value: 'EXPIRED_REVIEW_REQUIRED',
          label: i18nLabel(msg`Expired review required`),
          position: 4,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  outcomeReason: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'outcomeReason',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Outcome Reason`),
      description: i18nLabel(msg`Explanation of the check outcome`),
      icon: 'IconFileDescription',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  checkedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'checkedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Checked At`),
      description: i18nLabel(msg`When the conflict check was performed`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  expiresAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'expiresAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Expires At`),
      description: i18nLabel(msg`When the check result expires`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  waiverReference: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'waiverReference',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Waiver Reference`),
      description: i18nLabel(msg`Reference to a waiver if applicable`),
      icon: 'IconFileDescription',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviewNotes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviewNotes',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Review Notes`),
      description: i18nLabel(msg`Notes from the conflict review`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Conflict check record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
