import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildAiProviderCallLogStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'aiProviderCallLog', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'aiProviderCallLog'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Provider call log label`),
      icon: 'IconHistory',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  requestId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'requestId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Request Id`),
      description: i18nLabel(msg`Correlation id for the provider request`),
      icon: 'IconHash',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  providerName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'providerName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Provider`),
      description: i18nLabel(msg`AI provider name`),
      icon: 'IconBuilding',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  modelId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'modelId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Model Id`),
      description: i18nLabel(msg`Provider model identifier`),
      icon: 'IconTag',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  capability: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'capability',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Capability`),
      description: i18nLabel(msg`Agent capability exercised by the call`),
      icon: 'IconRobot',
      isNullable: false,
      isUIEditable: true,
      options: [
        {
          id: '8e317edb-80ff-424b-8bd1-2891a89f1891',
          value: 'ASSIGNMENT_INTAKE',
          label: i18nLabel(msg`Assignment Intake`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'af70744c-400e-46e3-959d-ed789e19168c',
          value: 'POSITION_SPECIFICATION_DRAFT',
          label: i18nLabel(msg`Position Specification Draft`),
          position: 1,
          color: 'purple',
        },
        {
          id: '05e3dc3b-7923-4a13-ad0c-375f596f5b81',
          value: 'RESEARCH_STRATEGY_DRAFT',
          label: i18nLabel(msg`Research Strategy Draft`),
          position: 2,
          color: 'green',
        },
        {
          id: 'faad8160-fdb8-465a-b8f6-5d52ad45348a',
          value: 'STATUS_REPORT_DRAFT',
          label: i18nLabel(msg`Status Report Draft`),
          position: 3,
          color: 'teal',
        },
        {
          id: 'a871955c-d1de-4bcf-a7f1-4d577f743a79',
          value: 'CANDIDATE_PRESENTATION_DRAFT',
          label: i18nLabel(msg`Candidate Presentation Draft`),
          position: 4,
          color: 'orange',
        },
        {
          id: '6445049b-b5d7-4622-8bb2-18df377ccee2',
          value: 'NL_SEARCH_FILTERS',
          label: i18nLabel(msg`NL Search Filters`),
          position: 5,
          color: 'pink',
        },
        {
          id: '04a07dc2-b786-4b3b-a3ee-f12ab5551353',
          value: 'TARGET_COMPANY_SUGGEST',
          label: i18nLabel(msg`Target Company Suggest`),
          position: 6,
          color: 'red',
        },
        {
          id: '297f8646-c236-457d-89f6-f1c2f5f9a10b',
          value: 'RELATIONSHIP_PATH_SUGGEST',
          label: i18nLabel(msg`Relationship Path Suggest`),
          position: 7,
          color: 'yellow',
        },
        {
          id: '7bca7138-2d7f-4c23-804c-2455e9c033e9',
          value: 'CRITERION_ASSESSMENT_SHADOW',
          label: i18nLabel(msg`Criterion Assessment Shadow`),
          position: 8,
          color: 'cyan',
        },
        {
          id: '212116af-ef09-4b29-b138-0b0fd6b6c623',
          value: 'BOARD_MATRIX_EVALUATION',
          label: i18nLabel(msg`Board Matrix Evaluation`),
          position: 9,
          color: 'sky',
        },
        {
          id: '0ffb3680-60a3-4bf4-b319-bad1d74be024',
          value: 'SEARCH_HEALTH_ADVISORY',
          label: i18nLabel(msg`Search Health Advisory`),
          position: 10,
          color: 'turquoise',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Outcome of the provider call`),
      icon: 'IconStatusChange',
      isNullable: false,
      isUIEditable: true,
      options: [
        {
          id: '4485058c-ae20-481e-9546-225bd8dad54c',
          value: 'SUCCESS',
          label: i18nLabel(msg`Success`),
          position: 0,
          color: 'green',
        },
        {
          id: '5eead7aa-dd8a-4ae9-a0e3-b75289845583',
          value: 'ERROR',
          label: i18nLabel(msg`Error`),
          position: 1,
          color: 'red',
        },
        {
          id: 'c5b9e00d-39bf-4e55-9204-d46a8ee0f4b8',
          value: 'TIMEOUT',
          label: i18nLabel(msg`Timeout`),
          position: 2,
          color: 'orange',
        },
        {
          id: '7070664f-a5ef-4517-afdf-9fd10a858086',
          value: 'GUARDRAIL_BLOCKED',
          label: i18nLabel(msg`Guardrail Blocked`),
          position: 3,
          color: 'purple',
        },
        {
          id: '126592f0-e6b6-4187-96a2-7865e548342c',
          value: 'RATE_LIMITED',
          label: i18nLabel(msg`Rate Limited`),
          position: 4,
          color: 'yellow',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  inputHash: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'inputHash',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Input Hash`),
      description: i18nLabel(msg`Hash of the call input for deduplication`),
      icon: 'IconHash',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  responseHash: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'responseHash',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Response Hash`),
      description: i18nLabel(msg`Hash of the provider response`),
      icon: 'IconHash',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  inputRedactionManifest: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'inputRedactionManifest',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Input Redaction Manifest`),
      description: i18nLabel(
        msg`Manifest of redactions applied to the call input`,
      ),
      icon: 'IconShieldLock',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  guardrailChecks: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'guardrailChecks',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Guardrail Checks`),
      description: i18nLabel(msg`Guardrail check outcomes for the call`),
      icon: 'IconShieldCheck',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  guardrailPolicyVersion: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'guardrailPolicyVersion',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Guardrail Policy Version`),
      description: i18nLabel(
        msg`Guardrail policy version applied to the call`,
      ),
      icon: 'IconShield',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  latencyMs: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'latencyMs',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Latency Ms`),
      description: i18nLabel(msg`Call latency in milliseconds`),
      icon: 'IconClock',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  tokenInputCount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'tokenInputCount',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Token Input Count`),
      description: i18nLabel(msg`Number of input tokens consumed`),
      icon: 'IconNumbers',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  tokenOutputCount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'tokenOutputCount',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Token Output Count`),
      description: i18nLabel(msg`Number of output tokens produced`),
      icon: 'IconNumbers',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  errorCode: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'errorCode',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Error Code`),
      description: i18nLabel(msg`Provider error code when the call failed`),
      icon: 'IconAlertTriangle',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  retentionPolicy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'retentionPolicy',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Retention Policy`),
      description: i18nLabel(msg`Retention policy for the call log`),
      icon: 'IconArchive',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'90d'",
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  retentionExpiresAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'retentionExpiresAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Retention Expires At`),
      description: i18nLabel(msg`When the call log is scheduled to expire`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  legalHold: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'legalHold',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Legal Hold`),
      description: i18nLabel(
        msg`Whether the call log is under legal hold`,
      ),
      icon: 'IconGavel',
      isNullable: false,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'subjectType',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Subject Type`),
      description: i18nLabel(msg`Type of subject the call acted on`),
      icon: 'IconTag',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'subjectId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Subject Id`),
      description: i18nLabel(msg`Identifier of the subject the call acted on`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  agentTurnRef: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'agentTurnRef',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Agent Turn Ref`),
      description: i18nLabel(
        msg`Free-text reference to the agent turn (not a relation)`,
      ),
      icon: 'IconLink',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  directusRequestLogId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'directusRequestLogId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Directus Request Log Id`),
      description: i18nLabel(msg`Directus source request log identifier`),
      icon: 'IconDatabase',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  metadata: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'metadata',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Metadata`),
      description: i18nLabel(msg`Additional call metadata`),
      icon: 'IconSettings',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  calledAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'calledAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Called At`),
      description: i18nLabel(msg`When the provider was called`),
      icon: 'IconCalendarCheck',
      isNullable: false,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  promptTemplateId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'promptTemplateId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Prompt Template`),
      description: i18nLabel(msg`Associated prompt template`),
      icon: 'IconMessage',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  promptTemplate: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'promptTemplate',
      label: i18nLabel(msg`Prompt Template`),
      description: i18nLabel(msg`Associated prompt template`),
      icon: 'IconMessage',
      isNullable: true,
      targetObjectName: 'aiPromptTemplate',
      targetFieldName: 'providerCallLogs',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.RESTRICT,
        joinColumnName: 'promptTemplateId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`AI provider call log record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconSearch',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
