import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildCandidatePresentationStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'candidatePresentation', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'candidatePresentation'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Presentation name`),
      icon: 'IconUser',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  version: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'version',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Version`),
      description: i18nLabel(msg`Presentation version`),
      icon: 'IconVersions',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Presentation status`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0006001',
          value: 'DRAFT',
          label: i18nLabel(msg`Draft`),
          position: 0,
          color: 'gray',
        },
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0006002',
          value: 'PENDING_REVIEW',
          label: i18nLabel(msg`Pending Review`),
          position: 1,
          color: 'yellow',
        },
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0006003',
          value: 'APPROVED',
          label: i18nLabel(msg`Approved`),
          position: 2,
          color: 'green',
        },
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0006004',
          value: 'PUBLISHED',
          label: i18nLabel(msg`Published`),
          position: 3,
          color: 'blue',
        },
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0006005',
          value: 'ARCHIVED',
          label: i18nLabel(msg`Archived`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceSnapshot: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceSnapshot',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Source Snapshot`),
      description: i18nLabel(msg`Snapshot of source data at time of presentation`),
      icon: 'IconCamera',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  restrictedFieldLeakageScanResult: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'restrictedFieldLeakageScanResult',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Restricted Field Leakage Scan Result`),
      description: i18nLabel(msg`Result of scanning for restricted field leakage`),
      icon: 'IconShield',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviewer: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'reviewer',
      label: i18nLabel(msg`Reviewer`),
      description: i18nLabel(msg`Person reviewing the presentation`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'reviewedPresentations',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'reviewerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviewerId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviewerId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Reviewer ID`),
      description: i18nLabel(msg`Reviewer ID`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviewedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviewedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Reviewed At`),
      description: i18nLabel(msg`When the presentation was reviewed`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviewDecision: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviewDecision',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Review Decision`),
      description: i18nLabel(msg`Outcome of the review`),
      icon: 'IconGavel',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0007001',
          value: 'PENDING',
          label: i18nLabel(msg`Pending`),
          position: 0,
          color: 'yellow',
        },
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0007002',
          value: 'APPROVED',
          label: i18nLabel(msg`Approved`),
          position: 1,
          color: 'green',
        },
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0007003',
          value: 'CHANGES_REQUESTED',
          label: i18nLabel(msg`Changes Requested`),
          position: 2,
          color: 'orange',
        },
        {
          id: 'aeb1a005-0060-4000-8005-aeb1a0007004',
          value: 'REJECTED',
          label: i18nLabel(msg`Rejected`),
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  approvedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'approvedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Approved At`),
      description: i18nLabel(msg`When the presentation was approved`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  publishedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'publishedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Published At`),
      description: i18nLabel(msg`When the presentation was published to client`),
      icon: 'IconCalendarSend',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  slateMembership: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'slateMembership',
      label: i18nLabel(msg`Slate Membership`),
      description: i18nLabel(msg`Associated slate membership`),
      icon: 'IconLayoutBoard',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'slateMembership',
      targetFieldName: 'presentations',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'slateMembershipId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  slateMembershipId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'slateMembershipId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Slate Membership ID`),
      description: i18nLabel(msg`Associated slate membership ID`),
      icon: 'IconLayoutBoard',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'candidacy',
      label: i18nLabel(msg`Candidacy`),
      description: i18nLabel(msg`Associated candidacy`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchCandidacy',
      targetFieldName: 'presentations',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'candidacyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacyId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'candidacyId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Candidacy ID`),
      description: i18nLabel(msg`Associated candidacy ID`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignment: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'searchAssignment',
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchAssignment',
      targetFieldName: 'presentations',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'searchAssignmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment ID`),
      description: i18nLabel(msg`Associated search assignment ID`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
