import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildGuaranteeCaseStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'guaranteeCase', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'guaranteeCase'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  owner: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'owner',
      label: i18nLabel(msg`Owner`),
      description: i18nLabel(msg`Owner of the guarantee case`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'ownedGuaranteeCases',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'ownerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Guarantee case name`),
      icon: 'IconShieldCheck',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Guarantee case status`),
      icon: 'IconStatusChange',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'ACTIVE'",
      options: [
        {
          id: 'd4d4e5e5-s001-4a04-8c04-ac11e000s001',
          value: 'ACTIVE',
          label: i18nLabel(msg`Active`),
          position: 0,
          color: 'green',
        },
        {
          id: 'd4d4e5e5-s002-4a04-8c04-ac11e000s002',
          value: 'CLAIMED',
          label: i18nLabel(msg`Claimed`),
          position: 1,
          color: 'yellow',
        },
        {
          id: 'd4d4e5e5-s003-4a04-8c04-ac11e000s003',
          value: 'RESOLVED',
          label: i18nLabel(msg`Resolved`),
          position: 2,
          color: 'purple',
        },
        {
          id: 'd4d4e5e5-s004-4a04-8c04-ac11e000s004',
          value: 'EXPIRED',
          label: i18nLabel(msg`Expired`),
          position: 3,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  activeFrom: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'activeFrom',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Active From`),
      description: i18nLabel(msg`When the guarantee becomes active`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  activeUntil: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'activeUntil',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Active Until`),
      description: i18nLabel(msg`When the guarantee expires`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  guaranteeType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'guaranteeType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Guarantee Type`),
      description: i18nLabel(msg`Type of guarantee`),
      icon: 'IconShield',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'd4d4e5e5-s011-4a04-8c04-ac11e000s011',
          value: 'STANDARD',
          label: i18nLabel(msg`Standard`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'd4d4e5e5-s012-4a04-8c04-ac11e000s012',
          value: 'EXTENDED',
          label: i18nLabel(msg`Extended`),
          position: 1,
          color: 'green',
        },
        {
          id: 'd4d4e5e5-s013-4a04-8c04-ac11e000s013',
          value: 'SPECIAL',
          label: i18nLabel(msg`Special`),
          position: 2,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  claimFiledAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'claimFiledAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Claim Filed At`),
      description: i18nLabel(msg`When the claim was filed`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  claimReason: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'claimReason',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Claim Reason`),
      description: i18nLabel(msg`Reason for the guarantee claim`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  claimAmount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'claimAmount',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Claim Amount`),
      description: i18nLabel(msg`Amount of the guarantee claim`),
      icon: 'IconMoneybag',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  claimCurrencyCode: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'claimCurrencyCode',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Claim Currency`),
      description: i18nLabel(msg`Currency code for the claim amount`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  claimOutcome: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'claimOutcome',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Claim Outcome`),
      description: i18nLabel(msg`Outcome of the guarantee claim`),
      icon: 'IconCheck',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'd4d4e5e5-s021-4a04-8c04-ac11e000s021',
          value: 'APPROVED',
          label: i18nLabel(msg`Approved`),
          position: 0,
          color: 'green',
        },
        {
          id: 'd4d4e5e5-s022-4a04-8c04-ac11e000s022',
          value: 'PARTIALLY_APPROVED',
          label: i18nLabel(msg`Partially Approved`),
          position: 1,
          color: 'yellow',
        },
        {
          id: 'd4d4e5e5-s023-4a04-8c04-ac11e000s023',
          value: 'DENIED',
          label: i18nLabel(msg`Denied`),
          position: 2,
          color: 'red',
        },
        {
          id: 'd4d4e5e5-s024-4a04-8c04-ac11e000s024',
          value: 'PENDING',
          label: i18nLabel(msg`Pending`),
          position: 3,
          color: 'blue',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  claimResolvedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'claimResolvedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Claim Resolved At`),
      description: i18nLabel(msg`When the claim was resolved`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  placement: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'placement',
      label: i18nLabel(msg`Placement`),
      description: i18nLabel(msg`Associated placement`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'placement',
      targetFieldName: 'guaranteeCases',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'placementId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  replacementPlacement: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'replacementPlacement',
      label: i18nLabel(msg`Replacement Placement`),
      description: i18nLabel(msg`Replacement placement if applicable`),
      icon: 'IconUserSwitch',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'placement',
      targetFieldName: 'replacementForGuaranteeCases',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'replacementPlacementId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignment: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'searchAssignment',
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'searchAssignment',
      targetFieldName: 'guaranteeCases',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'searchAssignmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(msg`The updater of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
