import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';

export const buildBoardCompositionProfileStandardFlatFieldMetadatas = ({ now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId, }: Omit<CreateStandardFieldArgs<'boardCompositionProfile', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'boardCompositionProfile'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid',},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Profile name`),icon:'IconUser',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  status: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'status',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Status`),description:i18nLabel(msg`Profile status`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'DRAFT'",options:[{id:'f0a1b2c3-s001-4000-8001-f0a1b2c3s001',value:'DRAFT',label:i18nLabel(msg`Draft`),position:0,color:'blue',},{id:'f0a1b2c3-s002-4000-8001-f0a1b2c3s002',value:'ACTIVE',label:i18nLabel(msg`Active`),position:1,color:'green',},{id:'f0a1b2c3-s003-4000-8001-f0a1b2c3s003',value:'ARCHIVED',label:i18nLabel(msg`Archived`),position:2,color:'grey',},],},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  targetBoardType: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'targetBoardType',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Target Board Type`),description:i18nLabel(msg`Type of board being targeted`),icon:'IconBuilding',isNullable:true,isUIEditable:true,options:[{id:'f0a1b2c3-s101-4000-8001-f0a1b2c3s101',value:'PUBLIC_FOR_PROFIT',label:i18nLabel(msg`Public For-Profit`),position:0,color:'blue',},{id:'f0a1b2c3-s102-4000-8001-f0a1b2c3s102',value:'PRIVATE_FOR_PROFIT',label:i18nLabel(msg`Private For-Profit`),position:1,color:'green',},{id:'f0a1b2c3-s103-4000-8001-f0a1b2c3s103',value:'NON_PROFIT',label:i18nLabel(msg`Non-Profit`),position:2,color:'orange',},{id:'f0a1b2c3-s104-4000-8001-f0a1b2c3s104',value:'ADVISORY',label:i18nLabel(msg`Advisory`),position:3,color:'purple',},{id:'f0a1b2c3-s105-4000-8001-f0a1b2c3s105',value:'PRIVATE_EQUITY_PORTFOLIO',label:i18nLabel(msg`Private Equity Portfolio`),position:4,color:'red',},],},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  industryPreference: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'industryPreference',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Industry Preference`),description:i18nLabel(msg`Preferred industry`),icon:'IconBuildingFactory',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  currentSize: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'currentSize',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Current Board Size`),description:i18nLabel(msg`Current board members`),icon:'IconUsers',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  targetSize: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'targetSize',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Target Board Size`),description:i18nLabel(msg`Target board members`),icon:'IconUsersGroup',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  notes: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'notes',type:FieldMetadataType.RICH_TEXT,label:i18nLabel(msg`Notes`),description:i18nLabel(msg`Additional notes`),icon:'IconFileText',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchAssignmentId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchAssignmentId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Search Assignment`),description:i18nLabel(msg`Associated search assignment`),icon:'IconSearch',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchAssignment: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchAssignment',type:FieldMetadataType.RELATION,label:i18nLabel(msg`Search Assignment`),description:i18nLabel(msg`Associated search assignment`),icon:'IconSearch',isSystem:true,isNullable:true,isUIEditable:false,settings:{foreignKeyName:'searchAssignmentId',},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`Creator`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`Last updater`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:{position:'first'},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Search Vector`),description:i18nLabel(msg`Search vector for full-text search`),icon:'IconSearch',isSystem:true,isNullable:true,isUIEditable:false,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
});
