import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildRelationshipEdgeStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'relationshipEdge', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'relationshipEdge'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourcePerson: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'sourcePerson',
      label: i18nLabel(msg`Source Person`),
      description: i18nLabel(msg`Source person in the relationship`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'person',
      targetFieldName: 'targetOfSourceRelationshipEdges',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'sourcePersonId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetPerson: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'targetPerson',
      label: i18nLabel(msg`Target Person`),
      description: i18nLabel(msg`Target person in the relationship`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'person',
      targetFieldName: 'targetOfTargetRelationshipEdges',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'targetPersonId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceCompany: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'sourceCompany',
      label: i18nLabel(msg`Source Company`),
      description: i18nLabel(msg`Source company in the relationship`),
      icon: 'IconBuilding',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'company',
      targetFieldName: 'sourceOfRelationshipEdges',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'sourceCompanyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetCompany: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'targetCompany',
      label: i18nLabel(msg`Target Company`),
      description: i18nLabel(msg`Target company in the relationship`),
      icon: 'IconBuilding',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'company',
      targetFieldName: 'targetOfRelationshipEdges',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'targetCompanyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  summary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'summary',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Summary`),
      description: i18nLabel(msg`Human-readable summary of the relationship`),
      icon: 'IconFileDescription',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  relationshipType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'relationshipType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Relationship Type`),
      description: i18nLabel(msg`Type of relationship between the entities`),
      icon: 'IconUsers',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'da7228d7-a3ea-4ee8-b202-bbcd699e43e4',
          value: 'COLLEAGUE',
          label: i18nLabel(msg`Colleague`),
          position: 0,
          color: 'blue',
        },
        {
          id: '9afe42d7-3396-414d-9446-ce8db489d71c',
          value: 'MANAGER_REPORT',
          label: i18nLabel(msg`Manager / Report`),
          position: 1,
          color: 'purple',
        },
        {
          id: 'd0abffb7-aa52-4f51-bfe7-367f60a008a1',
          value: 'MENTOR_MENTEE',
          label: i18nLabel(msg`Mentor / Mentee`),
          position: 2,
          color: 'green',
        },
        {
          id: '328c8be9-3a0b-4eba-9415-04e2078eec7e',
          value: 'CLIENT',
          label: i18nLabel(msg`Client`),
          position: 3,
          color: 'orange',
        },
        {
          id: '501db1ed-88fd-4f0f-8a0d-cb7591cd8789',
          value: 'VENDOR',
          label: i18nLabel(msg`Vendor`),
          position: 4,
          color: 'yellow',
        },
        {
          id: 'b35d5541-ccfb-4ec1-b125-ace1204c3996',
          value: 'INVESTOR',
          label: i18nLabel(msg`Investor`),
          position: 5,
          color: 'red',
        },
        {
          id: '6f52f2d0-e4a7-4761-8ace-7f6a82fa82ee',
          value: 'BOARD_COLLEAGUE',
          label: i18nLabel(msg`Board Colleague`),
          position: 6,
          color: 'sky',
        },
        {
          id: '51ff7478-9d18-4cdc-a251-1c56f8f92115',
          value: 'REFERENCE',
          label: i18nLabel(msg`Reference`),
          position: 7,
          color: 'teal',
        },
        {
          id: '0e36edf5-0ffe-4a47-bafd-5c6de3a3678b',
          value: 'REFERRAL_SOURCE',
          label: i18nLabel(msg`Referral Source`),
          position: 8,
          color: 'cyan',
        },
        {
          id: 'e78db600-88bf-4b96-bb7a-ec8479e5b483',
          value: 'ALUMNUS',
          label: i18nLabel(msg`Alumnus`),
          position: 9,
          color: 'indigo',
        },
        {
          id: '346b2809-f36e-4e04-8fca-4a69b7a66546',
          value: 'OTHER',
          label: i18nLabel(msg`Other`),
          position: 10,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  strength: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'strength',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Strength`),
      description: i18nLabel(msg`Strength of the relationship`),
      icon: 'IconBolt',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'MODERATE'",
      options: [
        {
          id: '692561c0-e69c-4b64-be99-1f512dd59a52',
          value: 'STRONG',
          label: i18nLabel(msg`Strong`),
          position: 0,
          color: 'green',
        },
        {
          id: '9319a64f-1ef8-48de-b3db-e43ca3b1f78b',
          value: 'MODERATE',
          label: i18nLabel(msg`Moderate`),
          position: 1,
          color: 'orange',
        },
        {
          id: '00b98390-d7a9-49ce-a255-d1b5bfee8630',
          value: 'WEAK',
          label: i18nLabel(msg`Weak`),
          position: 2,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  source: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'source',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Source`),
      description: i18nLabel(msg`How the relationship was recorded`),
      icon: 'IconSourceCode',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'MANUAL'",
      options: [
        {
          id: 'a6a2d69c-f4f9-4a84-b53b-b1eb7f1c51ce',
          value: 'MANUAL',
          label: i18nLabel(msg`Manual`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'b3d0c931-a891-4b02-81b4-afc0514c63a2',
          value: 'INFERRED',
          label: i18nLabel(msg`Inferred`),
          position: 1,
          color: 'purple',
        },
        {
          id: 'f68b4a90-30a2-4f5e-b4b0-400cbf7275b0',
          value: 'IMPORTED',
          label: i18nLabel(msg`Imported`),
          position: 2,
          color: 'orange',
        },
        {
          id: '309d3d63-9a36-4522-8309-55f802aeb9a3',
          value: 'ENRICHED',
          label: i18nLabel(msg`Enriched`),
          position: 3,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  confidenceLevel: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'confidenceLevel',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Confidence Level`),
      description: i18nLabel(msg`Confidence in the accuracy of the relationship data`),
      icon: 'IconShieldCheck',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'MEDIUM'",
      options: [
        {
          id: '41e051cf-7810-489f-984a-6124429bd85e',
          value: 'HIGH',
          label: i18nLabel(msg`High`),
          position: 0,
          color: 'green',
        },
        {
          id: '95b9ce11-0fe2-4bbd-a748-3bd7a9e457af',
          value: 'MEDIUM',
          label: i18nLabel(msg`Medium`),
          position: 1,
          color: 'orange',
        },
        {
          id: 'a84fd7d4-99ae-4e4d-82a2-14b6ef6a4575',
          value: 'LOW',
          label: i18nLabel(msg`Low`),
          position: 2,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  context: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'context',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Context`),
      description: i18nLabel(msg`Additional context about the relationship`),
      icon: 'IconInfoCircle',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  notes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'notes',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Notes`),
      description: i18nLabel(msg`Detailed notes about the relationship`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  observedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'observedAt',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Observed At`),
      description: i18nLabel(msg`When the relationship was observed or recorded`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Relationship edge record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
