import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT } from 'src/engine/metadata-modules/object-metadata/constants/standard-relation-field-properties.constant';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildSearchEngagementTermsStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'searchEngagementTerms', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'searchEngagementTerms'>,
  FlatFieldMetadata
> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Search Engagement Terms-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`The search engagement terms name`),
      icon: 'IconFileDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  termsType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'termsType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Terms Type`),
      description: i18nLabel(msg`Type of engagement terms`),
      icon: 'IconCategory',
      isNullable: false,
      defaultValue: "'ENGAGEMENT'",
      options: [
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000001',
          value: 'ENGAGEMENT',
          label: i18nLabel(msg`Engagement`),
          position: 0,
          color: 'green',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000002',
          value: 'AMENDMENT',
          label: i18nLabel(msg`Amendment`),
          position: 1,
          color: 'blue',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000003',
          value: 'RENEWAL',
          label: i18nLabel(msg`Renewal`),
          position: 2,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  feeStructure: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'feeStructure',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Fee Structure`),
      description: i18nLabel(msg`Fee structure for the engagement`),
      icon: 'IconCoin',
      isNullable: false,
      defaultValue: "'RETAINED'",
      options: [
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000004',
          value: 'RETAINED',
          label: i18nLabel(msg`Retained`),
          position: 0,
          color: 'green',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000005',
          value: 'CONTINGENCY',
          label: i18nLabel(msg`Contingency`),
          position: 1,
          color: 'orange',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000006',
          value: 'HYBRID',
          label: i18nLabel(msg`Hybrid`),
          position: 2,
          color: 'blue',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000007',
          value: 'FLAT',
          label: i18nLabel(msg`Flat`),
          position: 3,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  feePercentage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'feePercentage',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Fee Percentage`),
      description: i18nLabel(msg`Fee percentage for the engagement`),
      icon: 'IconPercentage',
      isNullable: true,
      settings: {
        decimals: 2,
        type: 'percentage',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  fixedFeeAmount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'fixedFeeAmount',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Fixed Fee Amount`),
      description: i18nLabel(msg`Fixed fee amount for the engagement`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  exclusivity: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'exclusivity',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Exclusivity`),
      description: i18nLabel(msg`Whether the engagement is exclusive`),
      icon: 'IconLock',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  exclusivityDurationMonths: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'exclusivityDurationMonths',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Exclusivity Duration (Months)`),
      description: i18nLabel(msg`Duration of exclusivity in months`),
      icon: 'IconCalendarTime',
      isNullable: true,
      settings: {
        decimals: 0,
        type: 'number',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  engagementStartDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'engagementStartDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Engagement Start Date`),
      description: i18nLabel(msg`Start date of the engagement`),
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  engagementEndDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'engagementEndDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Engagement End Date`),
      description: i18nLabel(msg`End date of the engagement`),
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  durationMonths: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'durationMonths',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Duration (Months)`),
      description: i18nLabel(msg`Duration of the engagement in months`),
      icon: 'IconCalendarTime',
      isNullable: true,
      settings: {
        decimals: 0,
        type: 'number',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  guaranteePeriodMonths: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'guaranteePeriodMonths',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Guarantee Period (Months)`),
      description: i18nLabel(msg`Guarantee period in months`),
      icon: 'IconShieldCheck',
      isNullable: true,
      settings: {
        decimals: 0,
        type: 'number',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  paymentSchedule: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'paymentSchedule',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Payment Schedule`),
      description: i18nLabel(msg`Payment schedule for the engagement`),
      icon: 'IconCalendarDollar',
      isNullable: false,
      defaultValue: "'MONTHLY'",
      options: [
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000008',
          value: 'MILESTONE',
          label: i18nLabel(msg`Milestone`),
          position: 0,
          color: 'blue',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba300000009',
          value: 'MONTHLY',
          label: i18nLabel(msg`Monthly`),
          position: 1,
          color: 'green',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba30000000a',
          value: 'UPFRONT',
          label: i18nLabel(msg`Upfront`),
          position: 2,
          color: 'purple',
        },
        {
          id: '7a3e4c9d-b2f8-1e5c-6d7a-8ba30000000b',
          value: 'ON_PLACEMENT',
          label: i18nLabel(msg`On Placement`),
          position: 3,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Search engagement terms record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  opportunity: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'opportunity',
      label: i18nLabel(msg`Opportunity`),
      description: i18nLabel(msg`Search engagement terms opportunity`),
      icon: 'IconTargetArrow',
      isNullable: true,
      targetObjectName: 'opportunity',
      targetFieldName: 'searchEngagementTerms',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'opportunityId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  taskTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'taskTargets',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.taskTarget.label,
      ),
      description: i18nLabel(msg`Tasks tied to the search engagement terms`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.taskTarget
        .icon,
      isUIEditable: false,
      isNullable: true,
      targetObjectName: 'taskTarget',
      targetFieldName: 'targetSearchEngagementTerms',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  noteTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'noteTargets',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.noteTarget.label,
      ),
      description: i18nLabel(msg`Notes tied to the search engagement terms`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.noteTarget
        .icon,
      isUIEditable: false,
      isNullable: true,
      targetObjectName: 'noteTarget',
      targetFieldName: 'targetSearchEngagementTerms',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attachments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'attachments',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.attachment.label,
      ),
      description: i18nLabel(
        msg`Attachments linked to the search engagement terms`,
      ),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.attachment
        .icon,
      isNullable: true,
      targetObjectName: 'attachment',
      targetFieldName: 'targetSearchEngagementTerms',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.timelineActivity
          .label,
      ),
      description: i18nLabel(
        msg`Timeline Activities linked to the search engagement terms.`,
      ),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT
        .timelineActivity.icon,
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetSearchEngagementTerms',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  owner: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'owner',
      label: i18nLabel(msg`Owner`),
      description: i18nLabel(msg`Search engagement terms owner`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'ownedSearchEngagementTerms',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'ownerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
