import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, RelationOnDeleteAction, RelationType } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildReferenceCheckStandardFlatFieldMetadatas = ({
  now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId,
}: Omit<CreateStandardFieldArgs<'referenceCheck', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'referenceCheck'>, FlatFieldMetadata> => ({
id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid'},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Reference check name`),icon:'IconFileDescription',isNullable:false,isUIEditable:true,defaultValue:"'New Reference Check'"},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
status: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'status',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Status`),description:i18nLabel(msg`Reference check status`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'NOT_STARTED'",options:[{id:'aeb1e000-2001-4000-8000-000000000001',value:'NOT_STARTED',label:i18nLabel(msg`Not Started`),position:0,color:'gray'},{id:'aeb1e000-2001-4000-8000-000000000002',value:'IN_PROGRESS',label:i18nLabel(msg`In Progress`),position:1,color:'blue'},{id:'aeb1e000-2001-4000-8000-000000000003',value:'COLLECTED',label:i18nLabel(msg`Collected`),position:2,color:'yellow'},{id:'aeb1e000-2001-4000-8000-000000000004',value:'VERIFIED',label:i18nLabel(msg`Verified`),position:3,color:'turquoise'},{id:'aeb1e000-2001-4000-8000-000000000005',value:'COMPLETED',label:i18nLabel(msg`Completed`),position:4,color:'green'},]},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
referenceName: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'referenceName',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Reference Name`),description:i18nLabel(msg`Name of the reference provider`),icon:'IconUser',isNullable:false,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
referenceTitle: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'referenceTitle',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Reference Title`),description:i18nLabel(msg`Title of the reference provider`),icon:'IconBriefcase',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
referenceOrganization: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'referenceOrganization',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Reference Organization`),description:i18nLabel(msg`Organization of the reference provider`),icon:'IconBuilding',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
referenceContact: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'referenceContact',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Reference Contact`),description:i18nLabel(msg`Contact information for the reference`),icon:'IconPhone',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
relationshipType: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'relationshipType',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Relationship Type`),description:i18nLabel(msg`Relationship between the referee and candidate`),icon:'IconLink',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
findings: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'findings',type:FieldMetadataType.RICH_TEXT,label:i18nLabel(msg`Findings`),description:i18nLabel(msg`Reference check findings`),icon:'IconFileText',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
verifiedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'verifiedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Verified At`),description:i18nLabel(msg`When the reference was verified`),icon:'IconCalendarClock',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
verifiedById: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'verifiedById',type:FieldMetadataType.UUID,label:i18nLabel(msg`Verified By`),description:i18nLabel(msg`Workspace member who verified the reference`),icon:'IconUserCheck',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchCandidacyId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchCandidacyId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Search Candidacy`),description:i18nLabel(msg`Associated search candidacy`),icon:'IconUser',isNullable:false,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchCandidacy: createStandardRelationFieldFlatMetadata({objectName,workspaceId,context:{type:FieldMetadataType.RELATION,morphId:null,fieldName:'searchCandidacy',label:i18nLabel(msg`Search Candidacy`),description:i18nLabel(msg`Candidacy this reference check is for`),icon:'IconUser',isNullable:false,isUIEditable:true,targetObjectName:'searchCandidacy',targetFieldName:'referenceChecks',settings:{relationType:RelationType.MANY_TO_ONE,onDelete:RelationOnDeleteAction.CASCADE,joinColumnName:'searchCandidacyId'}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`The creator of the record`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`The workspace member who last updated the record`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Reference check record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,defaultValue:0},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TS_VECTOR,label:i18nLabel(msg`Search vector`),description:i18nLabel(msg`Field used for full-text search`),icon:'IconUser',isSystem:true,isNullable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
});
