import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildOffLimitsRestrictionStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'offLimitsRestriction', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'offLimitsRestriction'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  company: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'company',
      label: i18nLabel(msg`Company`),
      description: i18nLabel(msg`Company subject to the restriction`),
      icon: 'IconBuilding',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'company',
      targetFieldName: 'offLimitsRestrictions',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  person: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'person',
      label: i18nLabel(msg`Person`),
      description: i18nLabel(msg`Person subject to the restriction`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'person',
      targetFieldName: 'offLimitsRestrictions',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'personId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  clientCompany: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'clientCompany',
      label: i18nLabel(msg`Client Company`),
      description: i18nLabel(msg`Client whose agreement created the restriction`),
      icon: 'IconBuilding',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'company',
      targetFieldName: 'clientOffLimitsRestrictions',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'clientCompanyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  summary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'summary',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Summary`),
      description: i18nLabel(
        msg`Human-readable label for the off-limits restriction`,
      ),
      icon: 'IconFileDescription',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  restrictionScope: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'restrictionScope',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Restriction Scope`),
      description: i18nLabel(msg`Scope of the off-limits restriction`),
      icon: 'IconHierarchy2',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'COMPANY_WIDE'",
      options: [
        {
          id: 'e111382e-0001-4000-8000-000000000001',
          value: 'COMPANY_WIDE',
          label: i18nLabel(msg`Company-wide`),
          position: 0,
          color: 'red',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000002',
          value: 'DEPARTMENT',
          label: i18nLabel(msg`Department`),
          position: 1,
          color: 'orange',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000003',
          value: 'DIVISION',
          label: i18nLabel(msg`Division`),
          position: 2,
          color: 'yellow',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000004',
          value: 'INDIVIDUAL',
          label: i18nLabel(msg`Individual`),
          position: 3,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  restrictionType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'restrictionType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Restriction Type`),
      description: i18nLabel(msg`Type of off-limits restriction`),
      icon: 'IconForbid2',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'OFF_LIMITS'",
      options: [
        {
          id: 'e111382e-0001-4000-8000-000000000010',
          value: 'OFF_LIMITS',
          label: i18nLabel(msg`Off-limits`),
          position: 0,
          color: 'red',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000011',
          value: 'DO_NOT_CONTACT',
          label: i18nLabel(msg`Do not contact`),
          position: 1,
          color: 'orange',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000012',
          value: 'NO_POACH',
          label: i18nLabel(msg`No poach`),
          position: 2,
          color: 'yellow',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000013',
          value: 'EXCLUSIVE_CLIENT',
          label: i18nLabel(msg`Exclusive client`),
          position: 3,
          color: 'purple',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000014',
          value: 'TALENT_MAPPING_ONLY',
          label: i18nLabel(msg`Talent mapping only`),
          position: 4,
          color: 'blue',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  basis: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'basis',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Basis`),
      description: i18nLabel(msg`Legal or policy basis for the restriction`),
      icon: 'IconScale',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'e111382e-0001-4000-8000-000000000020',
          value: 'CLIENT_AGREEMENT',
          label: i18nLabel(msg`Client agreement`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000021',
          value: 'FIRM_POLICY',
          label: i18nLabel(msg`Firm policy`),
          position: 1,
          color: 'turquoise',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000022',
          value: 'CANDIDATE_REQUEST',
          label: i18nLabel(msg`Candidate request`),
          position: 2,
          color: 'green',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000023',
          value: 'LEGAL',
          label: i18nLabel(msg`Legal`),
          position: 3,
          color: 'purple',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000024',
          value: 'PRIOR_PLACEMENT',
          label: i18nLabel(msg`Prior placement`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Current status of the restriction`),
      icon: 'IconStatusChange',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'ACTIVE'",
      options: [
        {
          id: 'e111382e-0001-4000-8000-000000000030',
          value: 'ACTIVE',
          label: i18nLabel(msg`Active`),
          position: 0,
          color: 'green',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000031',
          value: 'EXPIRED',
          label: i18nLabel(msg`Expired`),
          position: 1,
          color: 'gray',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000032',
          value: 'WAIVED',
          label: i18nLabel(msg`Waived`),
          position: 2,
          color: 'yellow',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000033',
          value: 'SUPERSEDED',
          label: i18nLabel(msg`Superseded`),
          position: 3,
          color: 'orange',
        },
        {
          id: 'e111382e-0001-4000-8000-000000000034',
          value: 'PENDING_REVIEW',
          label: i18nLabel(msg`Pending review`),
          position: 4,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  clientName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'clientName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Client Name`),
      description: i18nLabel(msg`Denormalized client name`),
      icon: 'IconBuilding',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  startDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'startDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Start Date`),
      description: i18nLabel(msg`Date the restriction takes effect`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  endDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'endDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`End Date`),
      description: i18nLabel(msg`Date the restriction expires`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  waiverReason: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'waiverReason',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Waiver Reason`),
      description: i18nLabel(msg`Reason the restriction was waived`),
      icon: 'IconFileDescription',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  waivedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'waivedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Waived At`),
      description: i18nLabel(msg`When the restriction was waived`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  notes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'notes',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Notes`),
      description: i18nLabel(msg`Additional notes about the restriction`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviewReason: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviewReason',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Review Reason`),
      description: i18nLabel(msg`Reason for pending review`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Off-limits restriction record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
