import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildClientFeedbackStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'clientFeedback', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'clientFeedback'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Feedback name`),
      icon: 'IconUser',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  feedbackType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'feedbackType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Feedback Type`),
      description: i18nLabel(msg`Type of feedback`),
      icon: 'IconCategory',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'CLIENT_INTERVIEW'",
      options: [
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0007001',
          value: 'CLIENT_INTERVIEW',
          label: i18nLabel(msg`Client Interview`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0007002',
          value: 'PRESENTATION_REVIEW',
          label: i18nLabel(msg`Presentation Review`),
          position: 1,
          color: 'purple',
        },
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0007003',
          value: 'GENERAL_IMPRESSION',
          label: i18nLabel(msg`General Impression`),
          position: 2,
          color: 'green',
        },
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0007004',
          value: 'AD_HOC',
          label: i18nLabel(msg`Ad Hoc`),
          position: 3,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  rating: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'rating',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Rating`),
      description: i18nLabel(msg`Feedback rating`),
      icon: 'IconStar',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0008001',
          value: 'VERY_POSITIVE',
          label: i18nLabel(msg`Very Positive`),
          position: 0,
          color: 'green',
        },
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0008002',
          value: 'POSITIVE',
          label: i18nLabel(msg`Positive`),
          position: 1,
          color: 'teal',
        },
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0008003',
          value: 'NEUTRAL',
          label: i18nLabel(msg`Neutral`),
          position: 2,
          color: 'yellow',
        },
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0008004',
          value: 'NEGATIVE',
          label: i18nLabel(msg`Negative`),
          position: 3,
          color: 'orange',
        },
        {
          id: 'aeb1a006-0060-4000-8006-aeb1a0008005',
          value: 'VERY_NEGATIVE',
          label: i18nLabel(msg`Very Negative`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  comments: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'comments',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Comments`),
      description: i18nLabel(msg`Detailed feedback comments`),
      icon: 'IconMessage',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  receivedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'receivedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Received At`),
      description: i18nLabel(msg`When the feedback was received`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  receivedFrom: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'receivedFrom',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Received From`),
      description: i18nLabel(msg`Who provided the feedback`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isSharedWithCandidate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isSharedWithCandidate',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Shared With Candidate`),
      description: i18nLabel(msg`Whether feedback was shared with candidate`),
      icon: 'IconShare',
      isNullable: true,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sharedWithCandidateAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sharedWithCandidateAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Shared With Candidate At`),
      description: i18nLabel(msg`When feedback was shared with candidate`),
      icon: 'IconCalendarShare',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'candidacy',
      label: i18nLabel(msg`Candidacy`),
      description: i18nLabel(msg`Associated candidacy`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchCandidacy',
      targetFieldName: 'clientFeedbacks',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'candidacyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacyId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'candidacyId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Candidacy ID`),
      description: i18nLabel(msg`Associated candidacy ID`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  slate: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'slate',
      label: i18nLabel(msg`Slate`),
      description: i18nLabel(msg`Associated slate`),
      icon: 'IconLayoutBoard',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchSlate',
      targetFieldName: 'clientFeedbacks',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'slateId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  slateId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'slateId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Slate ID`),
      description: i18nLabel(msg`Associated slate ID`),
      icon: 'IconLayoutBoard',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  presentation: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'presentation',
      label: i18nLabel(msg`Presentation`),
      description: i18nLabel(msg`Associated presentation`),
      icon: 'IconPresentation',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'candidatePresentation',
      targetFieldName: 'clientFeedbacks',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'presentationId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  presentationId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'presentationId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Presentation ID`),
      description: i18nLabel(msg`Associated presentation ID`),
      icon: 'IconPresentation',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignment: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'searchAssignment',
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchAssignment',
      targetFieldName: 'clientFeedbacks',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'searchAssignmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment ID`),
      description: i18nLabel(msg`Associated search assignment ID`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
