import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, RelationOnDeleteAction, RelationType } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildDiligenceCheckStandardFlatFieldMetadatas = ({
  now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId,
}: Omit<CreateStandardFieldArgs<'diligenceCheck', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'diligenceCheck'>, FlatFieldMetadata> => ({
id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid'},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Diligence check name`),icon:'IconFileDescription',isNullable:false,isUIEditable:true,defaultValue:"'New Diligence Check'"},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
diligenceType: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'diligenceType',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Diligence Type`),description:i18nLabel(msg`Type of diligence check`),icon:'IconShieldCheck',isNullable:false,isUIEditable:true,defaultValue:"'BACKGROUND_CHECK'",options:[{id:'aeb1f000-2001-4000-8000-000000000001',value:'BACKGROUND_CHECK',label:i18nLabel(msg`Background Check`),position:0,color:'blue'},{id:'aeb1f000-2001-4000-8000-000000000002',value:'CREDENTIAL_VERIFICATION',label:i18nLabel(msg`Credential Verification`),position:1,color:'turquoise'},{id:'aeb1f000-2001-4000-8000-000000000003',value:'SOCIAL_MEDIA',label:i18nLabel(msg`Social Media`),position:2,color:'purple'},{id:'aeb1f000-2001-4000-8000-000000000004',value:'REGULATORY',label:i18nLabel(msg`Regulatory`),position:3,color:'yellow'},{id:'aeb1f000-2001-4000-8000-000000000005',value:'LEGAL',label:i18nLabel(msg`Legal`),position:4,color:'red'},{id:'aeb1f000-2001-4000-8000-000000000006',value:'CONFLICT_OF_INTEREST',label:i18nLabel(msg`Conflict of Interest`),position:5,color:'orange'},{id:'aeb1f000-2001-4000-8000-000000000007',value:'OTHER',label:i18nLabel(msg`Other`),position:6,color:'gray'},]},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
status: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'status',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Status`),description:i18nLabel(msg`Diligence check status`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'NOT_STARTED'",options:[{id:'aeb1f000-2008-4000-8000-000000000001',value:'NOT_STARTED',label:i18nLabel(msg`Not Started`),position:0,color:'gray'},{id:'aeb1f000-2008-4000-8000-000000000002',value:'IN_PROGRESS',label:i18nLabel(msg`In Progress`),position:1,color:'blue'},{id:'aeb1f000-2008-4000-8000-000000000003',value:'PENDING_THIRD_PARTY',label:i18nLabel(msg`Pending Third Party`),position:2,color:'yellow'},{id:'aeb1f000-2008-4000-8000-000000000004',value:'COMPLETED_CLEAR',label:i18nLabel(msg`Completed \u2014 Clear`),position:3,color:'green'},{id:'aeb1f000-2008-4000-8000-000000000005',value:'COMPLETED_FLAGGED',label:i18nLabel(msg`Completed \u2014 Flagged`),position:4,color:'red'},]},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
findings: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'findings',type:FieldMetadataType.RICH_TEXT,label:i18nLabel(msg`Findings`),description:i18nLabel(msg`Diligence check findings`),icon:'IconFileText',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
recommendation: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'recommendation',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Recommendation`),description:i18nLabel(msg`Recommendation based on findings`),icon:'IconThumbUp',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
conductedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'conductedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Conducted At`),description:i18nLabel(msg`When the diligence check was conducted`),icon:'IconCalendarClock',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
conductedById: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'conductedById',type:FieldMetadataType.UUID,label:i18nLabel(msg`Conducted By`),description:i18nLabel(msg`Who conducted the diligence check`),icon:'IconUserCheck',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchCandidacyId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchCandidacyId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Search Candidacy`),description:i18nLabel(msg`Associated search candidacy`),icon:'IconUser',isNullable:false,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchCandidacy: createStandardRelationFieldFlatMetadata({objectName,workspaceId,context:{type:FieldMetadataType.RELATION,morphId:null,fieldName:'searchCandidacy',label:i18nLabel(msg`Search Candidacy`),description:i18nLabel(msg`Candidacy this diligence check is for`),icon:'IconUser',isNullable:false,isUIEditable:true,targetObjectName:'searchCandidacy',targetFieldName:'diligenceChecks',settings:{relationType:RelationType.MANY_TO_ONE,onDelete:RelationOnDeleteAction.CASCADE,joinColumnName:'searchCandidacyId'}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`The creator of the record`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`The workspace member who last updated the record`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Diligence check record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,defaultValue:0},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TS_VECTOR,label:i18nLabel(msg`Search vector`),description:i18nLabel(msg`Field used for full-text search`),icon:'IconUser',isSystem:true,isNullable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
});
