import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildAiPromptTemplateStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'aiPromptTemplate', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'aiPromptTemplate'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Prompt template display name`),
      icon: 'IconMessage',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  promptKey: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'promptKey',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Prompt Key`),
      description: i18nLabel(msg`Unique key identifying this prompt`),
      icon: 'IconTag',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  version: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'version',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Version`),
      description: i18nLabel(msg`Prompt template version`),
      icon: 'IconGitBranch',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Prompt template lifecycle status`),
      icon: 'IconStatusChange',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: '500d98c0-a219-464f-8e3b-583d182f5b32',
          value: 'DRAFT',
          label: i18nLabel(msg`Draft`),
          position: 0,
          color: 'gray',
        },
        {
          id: 'c5a958ba-7ddd-4745-ac1b-a71185983273',
          value: 'PUBLISHED',
          label: i18nLabel(msg`Published`),
          position: 1,
          color: 'green',
        },
        {
          id: 'b99439d3-1edc-4d88-8659-e9af8a1ec8bf',
          value: 'DEPRECATED',
          label: i18nLabel(msg`Deprecated`),
          position: 2,
          color: 'orange',
        },
        {
          id: '9be304b7-46a1-499d-aa99-65d5a5b6fd23',
          value: 'ARCHIVED',
          label: i18nLabel(msg`Archived`),
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  promptBody: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'promptBody',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Prompt Body`),
      description: i18nLabel(msg`Prompt body content`),
      icon: 'IconFileText',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  systemPrompt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'systemPrompt',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`System Prompt`),
      description: i18nLabel(msg`System prompt content`),
      icon: 'IconFileDescription',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  inputContract: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'inputContract',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Input Contract`),
      description: i18nLabel(msg`Contract describing prompt inputs`),
      icon: 'IconArrowsExchange',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  outputSchema: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'outputSchema',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Output Schema`),
      description: i18nLabel(msg`JSON schema for structured output`),
      icon: 'IconSchema',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  bannedInputs: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'bannedInputs',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Banned Inputs`),
      description: i18nLabel(msg`Banned input patterns`),
      icon: 'IconBan',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  guardrailPolicyVersion: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'guardrailPolicyVersion',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Guardrail Policy Version`),
      description: i18nLabel(
        msg`Guardrail policy version this prompt is governed by`,
      ),
      icon: 'IconShield',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  responseFormat: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'responseFormat',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Response Format`),
      description: i18nLabel(msg`Expected response format configuration`),
      icon: 'IconBrackets',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  modelConfiguration: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'modelConfiguration',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Model Configuration`),
      description: i18nLabel(msg`Model configuration parameters for this prompt`),
      icon: 'IconSettings',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  description: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'description',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Description`),
      description: i18nLabel(msg`Prompt template description`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  directusPromptId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'directusPromptId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Directus Prompt Id`),
      description: i18nLabel(msg`Directus source prompt identifier`),
      icon: 'IconTag',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceHash: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceHash',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source Hash`),
      description: i18nLabel(msg`Hash of the source definition`),
      icon: 'IconHash',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  publishedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'publishedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Published At`),
      description: i18nLabel(msg`When the prompt template was published`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deprecatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deprecatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deprecated At`),
      description: i18nLabel(msg`When the prompt template was deprecated`),
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetModelId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'targetModelId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Target Model`),
      description: i18nLabel(msg`Target AI model`),
      icon: 'IconBrain',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetModel: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'targetModel',
      label: i18nLabel(msg`Target Model`),
      description: i18nLabel(msg`Target AI model`),
      icon: 'IconBrain',
      isNullable: true,
      targetObjectName: 'aiModelRegistry',
      targetFieldName: 'promptTemplates',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'targetModelId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  providerCallLogs: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'providerCallLogs',
      label: i18nLabel(msg`Provider Call Logs`),
      description: i18nLabel(msg`Provider call logs for this prompt template`),
      icon: 'IconHistory',
      isNullable: true,
      targetObjectName: 'aiProviderCallLog',
      targetFieldName: 'promptTemplate',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  appAgents: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'appAgents',
      label: i18nLabel(msg`App Agents`),
      description: i18nLabel(msg`App agents using this prompt template`),
      icon: 'IconRobot',
      isNullable: true,
      targetObjectName: 'appAgents',
      targetFieldName: 'promptTemplate',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(msg`The workspace member who last updated the record`),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`AI prompt template record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconSearch',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
