import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildSlateMembershipStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'slateMembership', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'slateMembership'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Membership name`),
      icon: 'IconUser',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Position order in the slate`),
      icon: 'IconNumber',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Membership status`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'PENDING'",
      options: [
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0005001',
          value: 'PENDING',
          label: i18nLabel(msg`Pending`),
          position: 0,
          color: 'yellow',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0005002',
          value: 'ACTIVE',
          label: i18nLabel(msg`Active`),
          position: 1,
          color: 'green',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0005003',
          value: 'REMOVED',
          label: i18nLabel(msg`Removed`),
          position: 2,
          color: 'red',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0005004',
          value: 'PRESENTED',
          label: i18nLabel(msg`Presented`),
          position: 3,
          color: 'blue',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0005005',
          value: 'DECLINED',
          label: i18nLabel(msg`Declined`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  presentationConsentObtained: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'presentationConsentObtained',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Presentation Consent Obtained`),
      description: i18nLabel(msg`Whether candidate consented to presentation`),
      icon: 'IconCheck',
      isNullable: true,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  consentObtainedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'consentObtainedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Consent Obtained At`),
      description: i18nLabel(msg`When consent was obtained`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  consentExpiresAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'consentExpiresAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Consent Expires At`),
      description: i18nLabel(msg`When consent expires`),
      icon: 'IconCalendarOff',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  consentMethod: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'consentMethod',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Consent Method`),
      description: i18nLabel(msg`How consent was obtained`),
      icon: 'IconShield',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0006001',
          value: 'EMAIL',
          label: i18nLabel(msg`Email`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0006002',
          value: 'PHONE',
          label: i18nLabel(msg`Phone`),
          position: 1,
          color: 'green',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0006003',
          value: 'IN_PERSON',
          label: i18nLabel(msg`In Person`),
          position: 2,
          color: 'purple',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0006004',
          value: 'WRITTEN',
          label: i18nLabel(msg`Written`),
          position: 3,
          color: 'teal',
        },
        {
          id: 'aeb1a004-0060-4000-8004-aeb1a0006005',
          value: 'OTHER',
          label: i18nLabel(msg`Other`),
          position: 4,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  slate: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'slate',
      label: i18nLabel(msg`Slate`),
      description: i18nLabel(msg`Parent slate`),
      icon: 'IconLayoutBoard',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchSlate',
      targetFieldName: 'memberships',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'slateId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  slateId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'slateId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Slate ID`),
      description: i18nLabel(msg`Parent slate ID`),
      icon: 'IconLayoutBoard',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'candidacy',
      label: i18nLabel(msg`Candidacy`),
      description: i18nLabel(msg`Associated candidacy`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchCandidacy',
      targetFieldName: 'slateMemberships',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'candidacyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacyId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'candidacyId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Candidacy ID`),
      description: i18nLabel(msg`Associated candidacy ID`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
