import { msg } from '@lingui/core/macro';
import { DateDisplayFormat, FieldMetadataType } from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';

export const buildExternalIdentityMatchQueueStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'externalIdentityMatchQueue', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'externalIdentityMatchQueue'>,
  FlatFieldMetadata
> => ({
  // System fields
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Custom fields
  externalSystemName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'externalSystemName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`External System Name`),
      description: i18nLabel(msg`The external system this record came from`),
      icon: 'IconServer',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'directus'",
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  externalEntityName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'externalEntityName',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`External Entity Name`),
      description: i18nLabel(msg`The external entity collection this record belongs to`),
      icon: 'IconBox',
      isNullable: false,
      isUIEditable: true,
      options: [
        {
          id: '73bffa13-6788-45da-8e6a-fd9ece08577c',
          value: 'executives',
          label: i18nLabel(msg`Executives`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'bb343be3-9cbd-4b29-92ea-d091eb71796b',
          value: 'companies',
          label: i18nLabel(msg`Companies`),
          position: 1,
          color: 'green',
        },
        {
          id: '74c99745-96f7-464a-8e48-2a6582e54cdc',
          value: 'opportunities',
          label: i18nLabel(msg`Opportunities`),
          position: 2,
          color: 'purple',
        },
        {
          id: '887e1053-a375-4ac3-99d1-be2a178cf324',
          value: 'applications',
          label: i18nLabel(msg`Applications`),
          position: 3,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  externalRecordId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'externalRecordId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`External Record Id`),
      description: i18nLabel(msg`The external record identifier`),
      icon: 'IconHash',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  externalNaturalKey: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'externalNaturalKey',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`External Natural Key`),
      description: i18nLabel(msg`A natural key for the external record`),
      icon: 'IconKey',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  matchedTwentyEntityName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'matchedTwentyEntityName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Matched Twenty Entity Name`),
      description: i18nLabel(msg`The Twenty object matched for this record`),
      icon: 'IconTarget',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  matchConfidence: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'matchConfidence',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Match Confidence`),
      description: i18nLabel(msg`Confidence of the identity match`),
      icon: 'IconGauge',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'NONE'",
      options: [
        {
          id: '12cfc284-4864-4c86-8b2c-c4438303ba34',
          value: 'EXACT',
          label: i18nLabel(msg`Exact`),
          position: 0,
          color: 'green',
        },
        {
          id: 'b6f2aeba-2b50-4aa3-b6c2-a0514bb68f5c',
          value: 'HIGH',
          label: i18nLabel(msg`High`),
          position: 1,
          color: 'blue',
        },
        {
          id: '55602263-6783-46f4-ba75-3f73d132da7c',
          value: 'MEDIUM',
          label: i18nLabel(msg`Medium`),
          position: 2,
          color: 'yellow',
        },
        {
          id: '215bf119-c25b-4f21-9896-71c5e427636d',
          value: 'LOW',
          label: i18nLabel(msg`Low`),
          position: 3,
          color: 'orange',
        },
        {
          id: '9b81ec18-f6b5-4397-a49b-4df7f218f058',
          value: 'NONE',
          label: i18nLabel(msg`None`),
          position: 4,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidateMatches: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'candidateMatches',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Candidate Matches`),
      description: i18nLabel(
        msg`Candidate Twenty records for this external identity`,
      ),
      icon: 'IconList',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  resolutionState: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'resolutionState',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Resolution State`),
      description: i18nLabel(msg`How the identity match was resolved`),
      icon: 'IconCheck',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'PENDING'",
      options: [
        {
          id: '4e2a983a-781e-43f3-9224-6f5c9086ed7f',
          value: 'PENDING',
          label: i18nLabel(msg`Pending`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'f63319d6-58b6-42aa-8ef7-a2cd3587180d',
          value: 'RESOLVED_LINKED',
          label: i18nLabel(msg`Resolved Linked`),
          position: 1,
          color: 'green',
        },
        {
          id: 'ffec3685-422a-476c-8a10-a528d6be76c7',
          value: 'RESOLVED_NEW',
          label: i18nLabel(msg`Resolved New`),
          position: 2,
          color: 'purple',
        },
        {
          id: '4b18a787-0c9d-4ae3-aa35-8d9eb47cec16',
          value: 'RESOLVED_SKIP',
          label: i18nLabel(msg`Resolved Skip`),
          position: 3,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  resolvedTwentyEntityName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'resolvedTwentyEntityName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Resolved Twenty Entity Name`),
      description: i18nLabel(msg`The Twenty object chosen when resolving the match`),
      icon: 'IconTarget',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  resolvedTwentyRecordId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'resolvedTwentyRecordId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Resolved Twenty Record Id`),
      description: i18nLabel(msg`The Twenty record chosen when resolving the match`),
      icon: 'IconTarget',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  resolvedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'resolvedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Resolved At`),
      description: i18nLabel(msg`When the match was resolved`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  resolvedById: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'resolvedById',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Resolved By`),
      description: i18nLabel(msg`The workspace member who resolved the match`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  matchReasons: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'matchReasons',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Match Reasons`),
      description: i18nLabel(msg`Reasons explaining the identity match`),
      icon: 'IconList',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Identity match queue record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
