import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';

export const buildAnalyticsDomainMetricStandardFlatFieldMetadatas = ({ now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId, }: Omit<CreateStandardFieldArgs<'analyticsDomainMetric', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'analyticsDomainMetric'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid',},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Metric name`),icon:'IconUser',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  code: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'code',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Code`),description:i18nLabel(msg`Stable machine-readable metric key`),icon:'IconKey',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  description: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'description',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Description`),description:i18nLabel(msg`Human description of what the metric measures`),icon:'IconFileText',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  category: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'category',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Category`),description:i18nLabel(msg`Metric category`),icon:'IconCategory',isNullable:false,isUIEditable:true,defaultValue:"'PIPELINE'",options:[{id:'f0a1b2c3-m001-4000-8001-f0a1b2c3m001',value:'PIPELINE',label:i18nLabel(msg`Pipeline`),position:0,color:'blue',},{id:'f0a1b2c3-m002-4000-8001-f0a1b2c3m002',value:'FINANCIAL',label:i18nLabel(msg`Financial`),position:1,color:'green',},{id:'f0a1b2c3-m003-4000-8001-f0a1b2c3m003',value:'CLIENT',label:i18nLabel(msg`Client`),position:2,color:'orange',},{id:'f0a1b2c3-m004-4000-8001-f0a1b2c3m004',value:'CANDIDACY',label:i18nLabel(msg`Candidacy`),position:3,color:'purple',},{id:'f0a1b2c3-m005-4000-8001-f0a1b2c3m005',value:'PLACEMENT',label:i18nLabel(msg`Placement`),position:4,color:'red',},{id:'f0a1b2c3-m006-4000-8001-f0a1b2c3m006',value:'BOARD',label:i18nLabel(msg`Board`),position:5,color:'yellow',},{id:'f0a1b2c3-m007-4000-8001-f0a1b2c3m007',value:'RESEARCH',label:i18nLabel(msg`Research`),position:6,color:'grey',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  aggregationType: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'aggregationType',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Aggregation Type`),description:i18nLabel(msg`How the metric value is computed`),icon:'IconMath',isNullable:false,isUIEditable:true,defaultValue:"'COUNT'",options:[{id:'f0a1b2c3-m101-4000-8001-f0a1b2c3m101',value:'COUNT',label:i18nLabel(msg`Count`),position:0,color:'blue',},{id:'f0a1b2c3-m102-4000-8001-f0a1b2c3m102',value:'SUM',label:i18nLabel(msg`Sum`),position:1,color:'green',},{id:'f0a1b2c3-m103-4000-8001-f0a1b2c3m103',value:'AVERAGE',label:i18nLabel(msg`Average`),position:2,color:'orange',},{id:'f0a1b2c3-m104-4000-8001-f0a1b2c3m104',value:'RATIO',label:i18nLabel(msg`Ratio`),position:3,color:'purple',},{id:'f0a1b2c3-m105-4000-8001-f0a1b2c3m105',value:'PERCENTAGE',label:i18nLabel(msg`Percentage`),position:4,color:'red',},{id:'f0a1b2c3-m106-4000-8001-f0a1b2c3m106',value:'MEDIAN',label:i18nLabel(msg`Median`),position:5,color:'yellow',},{id:'f0a1b2c3-m107-4000-8001-f0a1b2c3m107',value:'PERCENTILE',label:i18nLabel(msg`Percentile`),position:6,color:'turquoise',},{id:'f0a1b2c3-m108-4000-8001-f0a1b2c3m108',value:'CUSTOM',label:i18nLabel(msg`Custom`),position:7,color:'pink',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  valueType: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'valueType',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Value Type`),description:i18nLabel(msg`Type of value the metric produces`),icon:'Icon123',isNullable:false,isUIEditable:true,defaultValue:"'NUMBER'",options:[{id:'f0a1b2c3-m201-4000-8001-f0a1b2c3m201',value:'NUMBER',label:i18nLabel(msg`Number`),position:0,color:'blue',},{id:'f0a1b2c3-m202-4000-8001-f0a1b2c3m202',value:'CURRENCY',label:i18nLabel(msg`Currency`),position:1,color:'green',},{id:'f0a1b2c3-m203-4000-8001-f0a1b2c3m203',value:'PERCENTAGE',label:i18nLabel(msg`Percentage`),position:2,color:'orange',},{id:'f0a1b2c3-m204-4000-8001-f0a1b2c3m204',value:'DURATION_DAYS',label:i18nLabel(msg`Duration Days`),position:3,color:'purple',},{id:'f0a1b2c3-m205-4000-8001-f0a1b2c3m205',value:'COUNT',label:i18nLabel(msg`Count`),position:4,color:'red',},{id:'f0a1b2c3-m206-4000-8001-f0a1b2c3m206',value:'RATIO',label:i18nLabel(msg`Ratio`),position:5,color:'yellow',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  timeWindow: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'timeWindow',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Time Window`),description:i18nLabel(msg`Default time window for aggregation`),icon:'IconCalendar',isNullable:false,isUIEditable:true,defaultValue:"'MONTH'",options:[{id:'f0a1b2c3-m301-4000-8001-f0a1b2c3m301',value:'POINT_IN_TIME',label:i18nLabel(msg`Point In Time`),position:0,color:'blue',},{id:'f0a1b2c3-m302-4000-8001-f0a1b2c3m302',value:'DAY',label:i18nLabel(msg`Day`),position:1,color:'green',},{id:'f0a1b2c3-m303-4000-8001-f0a1b2c3m303',value:'WEEK',label:i18nLabel(msg`Week`),position:2,color:'orange',},{id:'f0a1b2c3-m304-4000-8001-f0a1b2c3m304',value:'MONTH',label:i18nLabel(msg`Month`),position:3,color:'purple',},{id:'f0a1b2c3-m305-4000-8001-f0a1b2c3m305',value:'QUARTER',label:i18nLabel(msg`Quarter`),position:4,color:'red',},{id:'f0a1b2c3-m306-4000-8001-f0a1b2c3m306',value:'YEAR',label:i18nLabel(msg`Year`),position:5,color:'yellow',},{id:'f0a1b2c3-m307-4000-8001-f0a1b2c3m307',value:'TRAILING_30D',label:i18nLabel(msg`Trailing 30 Days`),position:6,color:'turquoise',},{id:'f0a1b2c3-m308-4000-8001-f0a1b2c3m308',value:'TRAILING_90D',label:i18nLabel(msg`Trailing 90 Days`),position:7,color:'pink',},{id:'f0a1b2c3-m309-4000-8001-f0a1b2c3m309',value:'TRAILING_365D',label:i18nLabel(msg`Trailing 365 Days`),position:8,color:'grey',},{id:'f0a1b2c3-m310-4000-8001-f0a1b2c3m310',value:'LIFETIME',label:i18nLabel(msg`Lifetime`),position:9,color:'blue',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  sourceObject: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'sourceObject',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Source Object`),description:i18nLabel(msg`Primary domain object queried for this metric`),icon:'IconDatabase',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  computationDescription: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'computationDescription',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Computation Description`),description:i18nLabel(msg`Natural-language description of how the metric is computed`),icon:'IconMathFunction',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  unit: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'unit',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Unit`),description:i18nLabel(msg`Display unit (USD, days, assignments)`),icon:'IconRuler',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  status: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'status',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Status`),description:i18nLabel(msg`Metric lifecycle status`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'DRAFT'",options:[{id:'f0a1b2c3-m401-4000-8001-f0a1b2c3m401',value:'DRAFT',label:i18nLabel(msg`Draft`),position:0,color:'blue',},{id:'f0a1b2c3-m402-4000-8001-f0a1b2c3m402',value:'ACTIVE',label:i18nLabel(msg`Active`),position:1,color:'green',},{id:'f0a1b2c3-m403-4000-8001-f0a1b2c3m403',value:'DEPRECATED',label:i18nLabel(msg`Deprecated`),position:2,color:'orange',},{id:'f0a1b2c3-m404-4000-8001-f0a1b2c3m404',value:'ARCHIVED',label:i18nLabel(msg`Archived`),position:3,color:'grey',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  isConfidential: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'isConfidential',type:FieldMetadataType.BOOLEAN,label:i18nLabel(msg`Is Confidential`),description:i18nLabel(msg`Whether this metric contains sensitive financial or personnel data`),icon:'IconEyeOff',isNullable:false,isUIEditable:true,defaultValue:false,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  tags: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'tags',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Tags`),description:i18nLabel(msg`Comma-separated or JSON grouping tags`),icon:'IconTag',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  ownerWorkspaceMemberId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'ownerWorkspaceMemberId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Owner`),description:i18nLabel(msg`Accountable owner of this metric`),icon:'IconUser',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  ownerWorkspaceMember: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'ownerWorkspaceMember',type:FieldMetadataType.RELATION,label:i18nLabel(msg`Owner`),description:i18nLabel(msg`Accountable owner of this metric`),icon:'IconUser',isSystem:true,isNullable:true,isUIEditable:false,settings:{foreignKeyName:'ownerWorkspaceMemberId',},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  snapshots: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'snapshots',type:FieldMetadataType.RELATION,label:i18nLabel(msg`Snapshots`),description:i18nLabel(msg`Materialized snapshot values for this metric`),icon:'IconChartHistogram',isSystem:true,isNullable:true,isUIEditable:false,settings:{foreignKeyName:'metricId',relationType:'ONE_TO_MANY',targetObjectName:'analyticsMetricSnapshot',},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`Creator`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`Last updater`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:{position:'first'},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Search Vector`),description:i18nLabel(msg`Search vector for full-text search`),icon:'IconSearch',isSystem:true,isNullable:true,isUIEditable:false,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
});
