import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildExecutiveProfileStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'executiveProfile', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'executiveProfile'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // person is the label identifier field — relates each executiveProfile to a single person record (one-to-one, enforced by unique index)
  person: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'person',
      label: i18nLabel(msg`Person`),
      description: i18nLabel(msg`Person`),
      icon: 'IconUser',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'person',
      targetFieldName: 'executiveProfile',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'personId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  headline: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'headline',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Headline`),
      description: i18nLabel(msg`Professional headline`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  summary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'summary',
      type: FieldMetadataType.LONG_TEXT,
      label: i18nLabel(msg`Summary`),
      description: i18nLabel(msg`Professional summary`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  currentCompany: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'currentCompany',
      label: i18nLabel(msg`Current Company`),
      description: i18nLabel(msg`Current company`),
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'company',
      targetFieldName: 'executiveProfiles',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'currentCompanyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  location: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'location',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Location`),
      description: i18nLabel(msg`Location`),
      icon: 'IconMapPin',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  yearsOfExperience: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'yearsOfExperience',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Years of Experience`),
      description: i18nLabel(msg`Years of professional experience`),
      icon: 'IconNumber',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  availabilityStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'availabilityStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Availability Status`),
      description: i18nLabel(msg`Candidate availability for new opportunities`),
      icon: 'IconStatusChange',
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'NOT_LOOKING'",
      options: [
        {
          id: '9972a2e7-1f5a-46d9-a95b-c06b6dc1cb47',
          value: 'NOT_LOOKING',
          label: i18nLabel(msg`Not Looking`),
          position: 0,
          color: 'gray',
        },
        {
          id: 'ec7c6593-7873-4d66-83ba-753ea7fe4525',
          value: 'OPEN_TO_OPPORTUNITIES',
          label: i18nLabel(msg`Open to Opportunities`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '6fcead9a-3044-4ffe-944c-24e029a6fbc4',
          value: 'ACTIVELY_LOOKING',
          label: i18nLabel(msg`Actively Looking`),
          position: 2,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  profileVisibility: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'profileVisibility',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Profile Visibility`),
      description: i18nLabel(msg`Who can see this profile`),
      icon: 'IconEye',
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'PRIVATE'",
      options: [
        {
          id: '76af0439-bdbb-4d83-8354-0dbeaa6c2f53',
          value: 'PRIVATE',
          label: i18nLabel(msg`Private`),
          position: 0,
          color: 'gray',
        },
        {
          id: '787d6012-a1ae-4275-a87f-3fdc8c30800f',
          value: 'FIRM_ONLY',
          label: i18nLabel(msg`Firm Only`),
          position: 1,
          color: 'blue',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isBoardReady: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isBoardReady',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Board Ready`),
      description: i18nLabel(msg`Candidate is ready for board placement`),
      icon: 'IconBriefcase',
      isNullable: false,
      isUIEditable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Provenance fields: denormalized onto executiveProfile for fast lookup without joining externalEntityLink.
  // externalEntityLink remains the canonical link ledger.
  sourceSystem: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceSystem',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Source System`),
      description: i18nLabel(msg`System of origin`),
      icon: 'IconDatabase',
      isNullable: false,
      isUIEditable: false,
      defaultValue: "'TWENTY'",
      options: [
        {
          id: 'a1095432-8b3a-4b1b-89cb-b77139299bee',
          value: 'TWENTY',
          label: i18nLabel(msg`Twenty`),
          position: 0,
          color: 'sky',
        },
        {
          id: '23e47c43-ec11-4f92-ae8f-142d1031a492',
          value: 'DIRECTUS',
          label: i18nLabel(msg`Directus`),
          position: 1,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceRecordId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceRecordId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source Record ID`),
      description: i18nLabel(msg`ID in the source system`),
      icon: 'IconId',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceUpdatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceUpdatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Source Updated At`),
      description: i18nLabel(msg`Last update timestamp from source system`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceHash: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceHash',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source Hash`),
      description: i18nLabel(msg`Content hash from source for change detection`),
      icon: 'IconHash',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Executive profile record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
