import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildAppAgentsStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'appAgents', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'appAgents'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Agent display name`),
      icon: 'IconRobot',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  agentKey: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'agentKey',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Agent Key`),
      description: i18nLabel(msg`Stable unique key for the agent`),
      icon: 'IconKey',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  capability: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'capability',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Capability`),
      description: i18nLabel(msg`Primary capability exercised by the agent`),
      icon: 'IconStars',
      isNullable: false,
      isUIEditable: true,
      options: [
        {
          id: 'ad914569-252e-4ffc-8b6f-26b467bca736',
          value: 'ASSIGNMENT_INTAKE',
          label: i18nLabel(msg`Assignment Intake`),
          position: 0,
          color: 'blue',
        },
        {
          id: '9b62ed88-1498-4e49-87b0-994baf39c88a',
          value: 'POSITION_SPECIFICATION_DRAFT',
          label: i18nLabel(msg`Position Specification Draft`),
          position: 1,
          color: 'purple',
        },
        {
          id: '859357b9-b002-43f4-920e-888f17f725a7',
          value: 'RESEARCH_STRATEGY_DRAFT',
          label: i18nLabel(msg`Research Strategy Draft`),
          position: 2,
          color: 'green',
        },
        {
          id: '78e0c4ac-ae8e-4712-9106-ef3ec713ff58',
          value: 'STATUS_REPORT_DRAFT',
          label: i18nLabel(msg`Status Report Draft`),
          position: 3,
          color: 'teal',
        },
        {
          id: '5700e362-f903-4792-a687-6b361b0c3f36',
          value: 'CANDIDATE_PRESENTATION_DRAFT',
          label: i18nLabel(msg`Candidate Presentation Draft`),
          position: 4,
          color: 'orange',
        },
        {
          id: '94576fb6-918f-4aaa-9c30-26d25207f337',
          value: 'NL_SEARCH_FILTERS',
          label: i18nLabel(msg`NL Search Filters`),
          position: 5,
          color: 'pink',
        },
        {
          id: '1ad23d8d-96b8-45a4-bc64-8d63610e6364',
          value: 'TARGET_COMPANY_SUGGEST',
          label: i18nLabel(msg`Target Company Suggest`),
          position: 6,
          color: 'red',
        },
        {
          id: '98865c17-25e4-4aea-bcfa-43ddd91d7a94',
          value: 'RELATIONSHIP_PATH_SUGGEST',
          label: i18nLabel(msg`Relationship Path Suggest`),
          position: 7,
          color: 'yellow',
        },
        {
          id: '58ac72bf-061c-411c-b702-eb23ff9fab28',
          value: 'CRITERION_ASSESSMENT_SHADOW',
          label: i18nLabel(msg`Criterion Assessment Shadow`),
          position: 8,
          color: 'cyan',
        },
        {
          id: 'c496b6fc-b824-4650-8ca4-cad739b0a139',
          value: 'BOARD_MATRIX_EVALUATION',
          label: i18nLabel(msg`Board Matrix Evaluation`),
          position: 9,
          color: 'sky',
        },
        {
          id: 'bf06dff4-ab87-41ad-b4e8-e832011dc4e4',
          value: 'SEARCH_HEALTH_ADVISORY',
          label: i18nLabel(msg`Search Health Advisory`),
          position: 10,
          color: 'turquoise',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Agent lifecycle status`),
      icon: 'IconStatusChange',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'ENABLED'",
      options: [
        {
          id: '02e929c3-40d1-4164-8f2b-dcf70a23d3a7',
          value: 'ENABLED',
          label: i18nLabel(msg`Enabled`),
          position: 0,
          color: 'green',
        },
        {
          id: '69f0888f-0ab4-41c7-8cc3-0bfdaf33e81c',
          value: 'DISABLED',
          label: i18nLabel(msg`Disabled`),
          position: 1,
          color: 'gray',
        },
        {
          id: '139508ae-5b66-4e60-96bd-fef71f9fb7d8',
          value: 'SHADOW_MODE',
          label: i18nLabel(msg`Shadow Mode`),
          position: 2,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  description: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'description',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Description`),
      description: i18nLabel(msg`Agent description`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  prompt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'prompt',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Prompt`),
      description: i18nLabel(msg`Default prompt for the agent`),
      icon: 'IconMessage',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  killSwitchEnabled: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'killSwitchEnabled',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Kill Switch Enabled`),
      description: i18nLabel(
        msg`Master kill switch; when false the agent cannot run`,
      ),
      icon: 'IconPower',
      isNullable: false,
      isUIEditable: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  approvalRequired: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'approvalRequired',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Approval Required`),
      description: i18nLabel(
        msg`Whether human approval is required before the agent runs`,
      ),
      icon: 'IconCircleCheck',
      isNullable: false,
      isUIEditable: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  humanReviewRequired: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'humanReviewRequired',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Human Review Required`),
      description: i18nLabel(
        msg`Whether human review of outputs is required`,
      ),
      icon: 'IconEye',
      isNullable: false,
      isUIEditable: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  consentRequired: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'consentRequired',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Consent Required`),
      description: i18nLabel(
        msg`Whether explicit subject consent is required before running`,
      ),
      icon: 'IconHandStop',
      isNullable: false,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isCustom: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isCustom',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Is Custom`),
      description: i18nLabel(msg`Whether the agent is user-defined`),
      icon: 'IconStar',
      isNullable: false,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  icon: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'icon',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Icon`),
      description: i18nLabel(msg`Icon name for the agent`),
      icon: 'IconPalette',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceHash: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceHash',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source Hash`),
      description: i18nLabel(msg`Hash of the agent source definition`),
      icon: 'IconHash',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  version: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'version',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Version`),
      description: i18nLabel(msg`Agent version`),
      icon: 'IconGitBranch',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  capabilities: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'capabilities',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Capabilities`),
      description: i18nLabel(msg`Capabilities configuration for the agent`),
      icon: 'IconSettings',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetModelId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'targetModelId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Target Model`),
      description: i18nLabel(msg`AI model registry entry used by this agent`),
      icon: 'IconBrain',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetModel: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'targetModel',
      label: i18nLabel(msg`Target Model`),
      description: i18nLabel(msg`AI model registry entry used by this agent`),
      icon: 'IconBrain',
      isNullable: true,
      targetObjectName: 'aiModelRegistry',
      targetFieldName: 'appAgents',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'targetModelId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  promptTemplateId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'promptTemplateId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Prompt Template`),
      description: i18nLabel(msg`Associated prompt template`),
      icon: 'IconMessage',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  promptTemplate: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'promptTemplate',
      label: i18nLabel(msg`Prompt Template`),
      description: i18nLabel(msg`Associated prompt template`),
      icon: 'IconMessage',
      isNullable: true,
      targetObjectName: 'aiPromptTemplate',
      targetFieldName: 'appAgents',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'promptTemplateId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`App agents record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconSearch',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
