import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildResearchCandidateStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'researchCandidate', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'researchCandidate'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  researchStrategy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'researchStrategy',
      label: i18nLabel(msg`Research Strategy`),
      description: i18nLabel(msg`Associated research strategy`),
      icon: 'IconChartDots',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'researchStrategy',
      targetFieldName: 'researchCandidates',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'researchStrategyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetCompany: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'targetCompany',
      label: i18nLabel(msg`Target Company`),
      description: i18nLabel(msg`Associated target company`),
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'targetCompany',
      targetFieldName: 'researchCandidates',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'targetCompanyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  executiveProfile: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'executiveProfile',
      label: i18nLabel(msg`Executive Profile`),
      description: i18nLabel(msg`Linked executive profile`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'executiveProfile',
      targetFieldName: 'researchCandidates',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'executiveProfileId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  person: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'person',
      label: i18nLabel(msg`Person`),
      description: i18nLabel(msg`Linked person record`),
      icon: 'IconUserCircle',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'person',
      targetFieldName: 'researchCandidates',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'personId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  currentTitle: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'currentTitle',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Current Title`),
      description: i18nLabel(msg`Current professional title`),
      icon: 'IconBriefcase',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  currentCompany: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'currentCompany',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Current Company`),
      description: i18nLabel(msg`Current company name`),
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  fitScore: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'fitScore',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Fit Score`),
      description: i18nLabel(msg`Candidate fit score (0-100)`),
      icon: 'IconNumbers',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  tier: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'tier',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Tier`),
      description: i18nLabel(msg`Research candidate tier`),
      icon: 'IconHierarchy',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'TIER_3'",
      options: [
        {
          id: '5bb2d10f-ae53-4373-b580-0e12414f5f64',
          value: 'TIER_1',
          label: i18nLabel(msg`Tier 1`),
          position: 0,
          color: 'red',
        },
        {
          id: 'e529445f-6fcc-4748-9a8c-05fa428ba974',
          value: 'TIER_2',
          label: i18nLabel(msg`Tier 2`),
          position: 1,
          color: 'blue',
        },
        {
          id: '165ec269-06fc-44a6-be6a-2bf611935223',
          value: 'TIER_3',
          label: i18nLabel(msg`Tier 3`),
          position: 2,
          color: 'gray',
        },
        {
          id: '9ce94087-126c-4ac3-9c80-da296afd7184',
          value: 'WATCHLIST',
          label: i18nLabel(msg`Watchlist`),
          position: 3,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Research candidate status`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'IDENTIFIED'",
      options: [
        {
          id: '0ac48ccb-c197-4911-a7c5-56d0896b033f',
          value: 'IDENTIFIED',
          label: i18nLabel(msg`Identified`),
          position: 0,
          color: 'blue',
        },
        {
          id: '0673cd6a-da6c-468c-a296-16ad725cf37d',
          value: 'RESEARCHING',
          label: i18nLabel(msg`Researching`),
          position: 1,
          color: 'purple',
        },
        {
          id: '1235e3f1-7229-4cb6-a31e-6af026696913',
          value: 'RESEARCHED',
          label: i18nLabel(msg`Researched`),
          position: 2,
          color: 'green',
        },
        {
          id: '8b40fb69-33e4-45ca-957f-5faa2de4ddeb',
          value: 'NOT_A_FIT',
          label: i18nLabel(msg`Not a Fit`),
          position: 3,
          color: 'red',
        },
        {
          id: '8bcd0eda-8612-4d91-b671-852f94da9a59',
          value: 'DUPLICATE',
          label: i18nLabel(msg`Duplicate`),
          position: 4,
          color: 'orange',
        },
        {
          id: 'a69bb4ff-f540-44b0-a674-0fc6a2836ea8',
          value: 'CONVERTED',
          label: i18nLabel(msg`Converted`),
          position: 5,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  source: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'source',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Source`),
      description: i18nLabel(msg`How the candidate was sourced`),
      icon: 'IconNetwork',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: '710634ef-4f1d-4df7-8c70-34322af05df3',
          value: 'DIRECT_OUTREACH',
          label: i18nLabel(msg`Direct Outreach`),
          position: 0,
          color: 'blue',
        },
        {
          id: '85e85dee-da44-441c-9653-63aea66ab517',
          value: 'REFERRAL',
          label: i18nLabel(msg`Referral`),
          position: 1,
          color: 'green',
        },
        {
          id: 'c49dc333-2944-4f4f-90cb-33142a8fbdea',
          value: 'NETWORK',
          label: i18nLabel(msg`Network`),
          position: 2,
          color: 'purple',
        },
        {
          id: 'bd1b5e5a-eec3-4847-b98b-3da0b9e9b17a',
          value: 'DATABASE',
          label: i18nLabel(msg`Database`),
          position: 3,
          color: 'orange',
        },
        {
          id: '5986254b-8d85-41ab-9618-9fd5262834c9',
          value: 'PARTNER',
          label: i18nLabel(msg`Partner`),
          position: 4,
          color: 'pink',
        },
        {
          id: '03eed283-339c-4ec6-8254-dc81f285c3e7',
          value: 'ENRICHMENT',
          label: i18nLabel(msg`Enrichment`),
          position: 5,
          color: 'yellow',
        },
        {
          id: '9ec32f7f-9157-4ce3-a544-f16cb1639745',
          value: 'OTHER',
          label: i18nLabel(msg`Other`),
          position: 6,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  rationale: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'rationale',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Rationale`),
      description: i18nLabel(msg`Why this candidate was identified`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  notes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'notes',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Notes`),
      description: i18nLabel(msg`Research notes`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lastContactedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lastContactedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last Contacted At`),
      description: i18nLabel(msg`When the candidate was last contacted`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Research candidate record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacies: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'candidacies',
      label: i18nLabel(msg`Candidacies`),
      description: i18nLabel(msg`Candidacies from this research candidate`),
      icon: 'IconUserSearch',
      isNullable: true,
      targetObjectName: 'searchCandidacy',
      targetFieldName: 'researchCandidate',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
