import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildPlacementStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'placement', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'placement'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  owner: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'owner',
      label: i18nLabel(msg`Owner`),
      description: i18nLabel(msg`Owner of the placement`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'ownedPlacements',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'ownerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Placement name`),
      icon: 'IconUserCheck',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Placement status`),
      icon: 'IconStatusChange',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'ACTIVE'",
      options: [
        {
          id: 'c3c3d4d4-s001-4a03-8c03-ac11e000s001',
          value: 'ACTIVE',
          label: i18nLabel(msg`Active`),
          position: 0,
          color: 'green',
        },
        {
          id: 'c3c3d4d4-s002-4a03-8c03-ac11e000s002',
          value: 'GUARANTEE_PERIOD',
          label: i18nLabel(msg`Guarantee Period`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'c3c3d4d4-s003-4a03-8c03-ac11e000s003',
          value: 'COMPLETED',
          label: i18nLabel(msg`Completed`),
          position: 2,
          color: 'purple',
        },
        {
          id: 'c3c3d4d4-s004-4a03-8c03-ac11e000s004',
          value: 'TERMINATED',
          label: i18nLabel(msg`Terminated`),
          position: 3,
          color: 'red',
        },
        {
          id: 'c3c3d4d4-s005-4a03-8c03-ac11e000s005',
          value: 'CANCELLED',
          label: i18nLabel(msg`Cancelled`),
          position: 4,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  placementDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'placementDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Placement Date`),
      description: i18nLabel(msg`Date of the placement`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  startDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'startDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Start Date`),
      description: i18nLabel(msg`Placement start date`),
      icon: 'IconCalendarEvent',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  endDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'endDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`End Date`),
      description: i18nLabel(msg`Placement end date`),
      icon: 'IconCalendarEvent',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  feeAmount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'feeAmount',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Fee Amount`),
      description: i18nLabel(msg`Placement fee amount`),
      icon: 'IconMoneybag',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  feeCurrencyCode: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'feeCurrencyCode',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Fee Currency`),
      description: i18nLabel(msg`Fee currency code`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  feeType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'feeType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Fee Type`),
      description: i18nLabel(msg`Type of placement fee`),
      icon: 'IconPercentage',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'c3c3d4d4-s011-4a03-8c03-ac11e000s011',
          value: 'PERCENTAGE_OF_SALARY',
          label: i18nLabel(msg`Percentage of Salary`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'c3c3d4d4-s012-4a03-8c03-ac11e000s012',
          value: 'FLAT_FEE',
          label: i18nLabel(msg`Flat Fee`),
          position: 1,
          color: 'green',
        },
        {
          id: 'c3c3d4d4-s013-4a03-8c03-ac11e000s013',
          value: 'RETAINED',
          label: i18nLabel(msg`Retained`),
          position: 2,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  feeCalculation: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'feeCalculation',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Fee Calculation`),
      description: i18nLabel(msg`Details of the fee calculation`),
      icon: 'IconCalculator',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  commissionableAmount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'commissionableAmount',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Commissionable Amount`),
      description: i18nLabel(msg`Amount used for commission calculation`),
      icon: 'IconCash',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  invoiceReference: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'invoiceReference',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Invoice Reference`),
      description: i18nLabel(msg`Invoice reference number`),
      icon: 'IconFileInvoice',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  guaranteePeriodMonths: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'guaranteePeriodMonths',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Guarantee Period (months)`),
      description: i18nLabel(msg`Guarantee period in months`),
      icon: 'IconShieldCheck',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  guaranteeEndDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'guaranteeEndDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Guarantee End Date`),
      description: i18nLabel(msg`Date when the guarantee period ends`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  billingContact: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'billingContact',
      label: i18nLabel(msg`Billing Contact`),
      description: i18nLabel(msg`Billing contact for the placement`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'person',
      targetFieldName: 'placements',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'billingContactId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  placementConfirmedBy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'placementConfirmedBy',
      label: i18nLabel(msg`Confirmed By`),
      description: i18nLabel(msg`Who confirmed the placement`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'confirmedPlacements',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'placementConfirmedById',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'candidacy',
      label: i18nLabel(msg`Candidacy`),
      description: i18nLabel(msg`Associated candidacy`),
      icon: 'IconUserSearch',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'searchCandidacy',
      targetFieldName: 'placements',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'candidacyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  offerNegotiation: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'offerNegotiation',
      label: i18nLabel(msg`Offer Negotiation`),
      description: i18nLabel(msg`Associated offer negotiation`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'offerNegotiation',
      targetFieldName: 'placements',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'offerNegotiationId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignment: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'searchAssignment',
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: true,
      targetObjectName: 'searchAssignment',
      targetFieldName: 'placements',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'searchAssignmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(msg`The updater of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
