import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';

export const buildAnalyticsDashboardConfigStandardFlatFieldMetadatas = ({ now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId, }: Omit<CreateStandardFieldArgs<'analyticsDashboardConfig', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'analyticsDashboardConfig'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid',},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Dashboard name`),icon:'IconUser',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  description: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'description',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Description`),description:i18nLabel(msg`Dashboard description`),icon:'IconFileText',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  scope: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'scope',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Scope`),description:i18nLabel(msg`Dashboard scope`),icon:'IconEye',isNullable:false,isUIEditable:true,defaultValue:"'FIRM_WIDE'",options:[{id:'f0a1b2c3-d001-4000-8001-f0a1b2c3d001',value:'FIRM_WIDE',label:i18nLabel(msg`Firm Wide`),position:0,color:'blue',},{id:'f0a1b2c3-d002-4000-8001-f0a1b2c3d002',value:'PRACTICE_GROUP',label:i18nLabel(msg`Practice Group`),position:1,color:'green',},{id:'f0a1b2c3-d003-4000-8001-f0a1b2c3d003',value:'TEAM',label:i18nLabel(msg`Team`),position:2,color:'orange',},{id:'f0a1b2c3-d004-4000-8001-f0a1b2c3d004',value:'CLIENT',label:i18nLabel(msg`Client`),position:3,color:'purple',},{id:'f0a1b2c3-d005-4000-8001-f0a1b2c3d005',value:'ASSIGNMENT',label:i18nLabel(msg`Assignment`),position:4,color:'red',},{id:'f0a1b2c3-d006-4000-8001-f0a1b2c3d006',value:'PERSONAL',label:i18nLabel(msg`Personal`),position:5,color:'yellow',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  audience: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'audience',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Audience`),description:i18nLabel(msg`Target audience for this dashboard`),icon:'IconUsers',isNullable:false,isUIEditable:true,defaultValue:"'ALL_INTERNAL'",options:[{id:'f0a1b2c3-d101-4000-8001-f0a1b2c3d101',value:'MANAGING_PARTNER',label:i18nLabel(msg`Managing Partner`),position:0,color:'blue',},{id:'f0a1b2c3-d102-4000-8001-f0a1b2c3d102',value:'PRACTICE_LEADER',label:i18nLabel(msg`Practice Leader`),position:1,color:'green',},{id:'f0a1b2c3-d103-4000-8001-f0a1b2c3d103',value:'FINANCE_OPS',label:i18nLabel(msg`Finance Ops`),position:2,color:'orange',},{id:'f0a1b2c3-d104-4000-8001-f0a1b2c3d104',value:'SEARCH_PARTNER',label:i18nLabel(msg`Search Partner`),position:3,color:'purple',},{id:'f0a1b2c3-d105-4000-8001-f0a1b2c3d105',value:'ALL_INTERNAL',label:i18nLabel(msg`All Internal`),position:4,color:'red',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  metricCodes: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'metricCodes',type:FieldMetadataType.JSON,label:i18nLabel(msg`Metric Codes`),description:i18nLabel(msg`Ordered list of metric codes displayed in this dashboard`),icon:'IconListNumbers',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  layout: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'layout',type:FieldMetadataType.JSON,label:i18nLabel(msg`Layout`),description:i18nLabel(msg`Widget grid positions and chart types per metric`),icon:'IconLayoutDashboard',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  filters: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'filters',type:FieldMetadataType.JSON,label:i18nLabel(msg`Filters`),description:i18nLabel(msg`Default filter values (time range, practice group, client, owner)`),icon:'IconFilter',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  defaultTimeRange: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'defaultTimeRange',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Default Time Range`),description:i18nLabel(msg`Default time window when dashboard loads`),icon:'IconCalendar',isNullable:false,isUIEditable:true,defaultValue:"'MONTH'",options:[{id:'f0a1b2c3-d201-4000-8001-f0a1b2c3d201',value:'POINT_IN_TIME',label:i18nLabel(msg`Point In Time`),position:0,color:'blue',},{id:'f0a1b2c3-d202-4000-8001-f0a1b2c3d202',value:'DAY',label:i18nLabel(msg`Day`),position:1,color:'green',},{id:'f0a1b2c3-d203-4000-8001-f0a1b2c3d203',value:'WEEK',label:i18nLabel(msg`Week`),position:2,color:'orange',},{id:'f0a1b2c3-d204-4000-8001-f0a1b2c3d204',value:'MONTH',label:i18nLabel(msg`Month`),position:3,color:'purple',},{id:'f0a1b2c3-d205-4000-8001-f0a1b2c3d205',value:'QUARTER',label:i18nLabel(msg`Quarter`),position:4,color:'red',},{id:'f0a1b2c3-d206-4000-8001-f0a1b2c3d206',value:'YEAR',label:i18nLabel(msg`Year`),position:5,color:'yellow',},{id:'f0a1b2c3-d207-4000-8001-f0a1b2c3d207',value:'TRAILING_30D',label:i18nLabel(msg`Trailing 30 Days`),position:6,color:'turquoise',},{id:'f0a1b2c3-d208-4000-8001-f0a1b2c3d208',value:'TRAILING_90D',label:i18nLabel(msg`Trailing 90 Days`),position:7,color:'pink',},{id:'f0a1b2c3-d209-4000-8001-f0a1b2c3d209',value:'TRAILING_365D',label:i18nLabel(msg`Trailing 365 Days`),position:8,color:'grey',},{id:'f0a1b2c3-d210-4000-8001-f0a1b2c3d210',value:'LIFETIME',label:i18nLabel(msg`Lifetime`),position:9,color:'blue',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  refreshFrequency: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'refreshFrequency',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Refresh Frequency`),description:i18nLabel(msg`How often this dashboard refreshes`),icon:'IconRefresh',isNullable:false,isUIEditable:true,defaultValue:"'DAILY'",options:[{id:'f0a1b2c3-d301-4000-8001-f0a1b2c3d301',value:'REAL_TIME',label:i18nLabel(msg`Real Time`),position:0,color:'blue',},{id:'f0a1b2c3-d302-4000-8001-f0a1b2c3d302',value:'HOURLY',label:i18nLabel(msg`Hourly`),position:1,color:'green',},{id:'f0a1b2c3-d303-4000-8001-f0a1b2c3d303',value:'DAILY',label:i18nLabel(msg`Daily`),position:2,color:'orange',},{id:'f0a1b2c3-d304-4000-8001-f0a1b2c3d304',value:'WEEKLY',label:i18nLabel(msg`Weekly`),position:3,color:'purple',},{id:'f0a1b2c3-d305-4000-8001-f0a1b2c3d305',value:'MANUAL',label:i18nLabel(msg`Manual`),position:4,color:'red',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  isShared: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'isShared',type:FieldMetadataType.BOOLEAN,label:i18nLabel(msg`Is Shared`),description:i18nLabel(msg`Whether this dashboard is shared or personal`),icon:'IconShare',isNullable:false,isUIEditable:true,defaultValue:false,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  status: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'status',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Status`),description:i18nLabel(msg`Dashboard lifecycle status`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'DRAFT'",options:[{id:'f0a1b2c3-d401-4000-8001-f0a1b2c3d401',value:'DRAFT',label:i18nLabel(msg`Draft`),position:0,color:'blue',},{id:'f0a1b2c3-d402-4000-8001-f0a1b2c3d402',value:'ACTIVE',label:i18nLabel(msg`Active`),position:1,color:'green',},{id:'f0a1b2c3-d403-4000-8001-f0a1b2c3d403',value:'DEPRECATED',label:i18nLabel(msg`Deprecated`),position:2,color:'orange',},{id:'f0a1b2c3-d404-4000-8001-f0a1b2c3d404',value:'ARCHIVED',label:i18nLabel(msg`Archived`),position:3,color:'grey',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  ownerWorkspaceMemberId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'ownerWorkspaceMemberId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Owner`),description:i18nLabel(msg`Dashboard owner`),icon:'IconUser',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  ownerWorkspaceMember: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'ownerWorkspaceMember',type:FieldMetadataType.RELATION,label:i18nLabel(msg`Owner`),description:i18nLabel(msg`Dashboard owner`),icon:'IconUser',isSystem:true,isNullable:true,isUIEditable:false,settings:{foreignKeyName:'ownerWorkspaceMemberId',},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`Creator`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`Last updater`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:{position:'first'},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Search Vector`),description:i18nLabel(msg`Search vector for full-text search`),icon:'IconSearch',isSystem:true,isNullable:true,isUIEditable:false,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
});
