import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildTargetCompanyStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'targetCompany', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'targetCompany'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  marketMap: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'marketMap',
      label: i18nLabel(msg`Market Map`),
      description: i18nLabel(msg`Parent market map`),
      icon: 'IconMap',
      isNullable: false,
      isUIEditable: false,
      targetObjectName: 'marketMap',
      targetFieldName: 'targetCompanies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'marketMapId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  company: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'company',
      label: i18nLabel(msg`Company`),
      description: i18nLabel(msg`Linked company record`),
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'company',
      targetFieldName: 'targetCompanies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  researchCandidates: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'researchCandidates',
      label: i18nLabel(msg`Research Candidates`),
      description: i18nLabel(msg`Research candidates at this target company`),
      icon: 'IconUserSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'researchCandidate',
      targetFieldName: 'targetCompany',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
        onDelete: RelationOnDeleteAction.SET_NULL,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  companyName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'companyName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Company Name`),
      description: i18nLabel(msg`Target company name`),
      icon: 'IconBuildingSkyscraper',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  domain: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'domain',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Domain`),
      description: i18nLabel(msg`Company domain`),
      icon: 'IconWorld',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  industry: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'industry',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Industry`),
      description: i18nLabel(msg`Company industry`),
      icon: 'IconBuildingFactory',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sizeBand: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sizeBand',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Size Band`),
      description: i18nLabel(msg`Company size band`),
      icon: 'IconArrowsSort',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'be00adab-643d-48ce-ab2c-ebe662507f65',
          value: 'STARTUP',
          label: i18nLabel(msg`Startup`),
          position: 0,
          color: 'gray',
        },
        {
          id: '9709438c-d451-48ed-9182-dbcc7de932a8',
          value: 'SMALL',
          label: i18nLabel(msg`Small`),
          position: 1,
          color: 'blue',
        },
        {
          id: '73e50101-118b-4338-9273-728f64ed9d34',
          value: 'MID_MARKET',
          label: i18nLabel(msg`Mid Market`),
          position: 2,
          color: 'purple',
        },
        {
          id: 'b5c2debb-fea5-4e8f-88cd-487980279f59',
          value: 'LARGE',
          label: i18nLabel(msg`Large`),
          position: 3,
          color: 'orange',
        },
        {
          id: '057b9f00-b4e9-4c88-a5ed-74a725f174d3',
          value: 'ENTERPRISE',
          label: i18nLabel(msg`Enterprise`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  tier: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'tier',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Tier`),
      description: i18nLabel(msg`Target company tier`),
      icon: 'IconHierarchy',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'TIER_2'",
      options: [
        {
          id: '0309599a-a54b-4d4b-b77a-0672e077c376',
          value: 'TIER_1',
          label: i18nLabel(msg`Tier 1`),
          position: 0,
          color: 'red',
        },
        {
          id: '317b2820-4298-474b-94c3-d1f3b6e6fff7',
          value: 'TIER_2',
          label: i18nLabel(msg`Tier 2`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'e3cebe41-6e68-40ee-a682-4a903698f695',
          value: 'TIER_3',
          label: i18nLabel(msg`Tier 3`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attractiveness: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'attractiveness',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Attractiveness`),
      description: i18nLabel(msg`Attractiveness of this target`),
      icon: 'IconStar',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'MEDIUM'",
      options: [
        {
          id: '27e8ef3e-7d19-46fc-835f-3f4ddb3eb11b',
          value: 'HIGH',
          label: i18nLabel(msg`High`),
          position: 0,
          color: 'green',
        },
        {
          id: 'cb8509d3-c1c1-4086-bdcc-d80d1a6a5e6e',
          value: 'MEDIUM',
          label: i18nLabel(msg`Medium`),
          position: 1,
          color: 'blue',
        },
        {
          id: '4e65b05a-058c-4107-b1b3-b74a35c978ca',
          value: 'LOW',
          label: i18nLabel(msg`Low`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  headquartersLocation: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'headquartersLocation',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Headquarters Location`),
      description: i18nLabel(msg`Headquarters location`),
      icon: 'IconMapPin',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  rationale: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'rationale',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Rationale`),
      description: i18nLabel(msg`Why this company is targeted`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Target company record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
