import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';

export const buildDirectorIndependenceReviewStandardFlatFieldMetadatas = ({ now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId, }: Omit<CreateStandardFieldArgs<'directorIndependenceReview', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'directorIndependenceReview'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid',},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Review name`),icon:'IconUser',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  status: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'status',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Status`),description:i18nLabel(msg`Review status`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'PENDING'",options:[{id:'f0a1b2c3-s301-4000-8004-f0a1b2c3s001',value:'PENDING',label:i18nLabel(msg`Pending`),position:0,color:'blue',},{id:'f0a1b2c3-s302-4000-8004-f0a1b2c3s002',value:'IN_REVIEW',label:i18nLabel(msg`In Review`),position:1,color:'yellow',},{id:'f0a1b2c3-s303-4000-8004-f0a1b2c3s003',value:'COMPLETED',label:i18nLabel(msg`Completed`),position:2,color:'green',},{id:'f0a1b2c3-s304-4000-8004-f0a1b2c3s004',value:'FLAGGED',label:i18nLabel(msg`Flagged`),position:3,color:'red',},],},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  reviewDate: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'reviewDate',type:FieldMetadataType.DATE,label:i18nLabel(msg`Review Date`),description:i18nLabel(msg`Date of the review`),icon:'IconCalendar',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  findings: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'findings',type:FieldMetadataType.RICH_TEXT,label:i18nLabel(msg`Findings`),description:i18nLabel(msg`Review findings`),icon:'IconFileText',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  reviewerId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'reviewerId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Reviewer`),description:i18nLabel(msg`Reviewer workspace member`),icon:'IconUserCheck',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchCandidacyId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchCandidacyId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Search Candidacy`),description:i18nLabel(msg`Associated search candidacy`),icon:'IconUser',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`Creator`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`Last updater`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:{position:'first'},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Search Vector`),description:i18nLabel(msg`Search vector for full-text search`),icon:'IconSearch',isSystem:true,isNullable:true,isUIEditable:false,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
});
