import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildSearchCandidacyStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'searchCandidacy', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'searchCandidacy'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Candidacy label`),
      icon: 'IconUser',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Candidacy status`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'IDENTIFIED'",
      options: [
        {
          id: '2c4a1b3e-5d6f-4a7b-8c9d-0e1f2a3b4c5d',
          value: 'IDENTIFIED',
          label: i18nLabel(msg`Identified`),
          position: 0,
          color: 'blue',
        },
        {
          id: '3d5b2c4f-6e7a-4b8c-9d0e-1f2a3b4c5d6e',
          value: 'RESEARCHING',
          label: i18nLabel(msg`Researching`),
          position: 1,
          color: 'purple',
        },
        {
          id: '4e6c3d5a-7f8b-4c9d-0e1f-2a3b4c5d6e7f',
          value: 'RESEARCH_COMPLETE',
          label: i18nLabel(msg`Research Complete`),
          position: 2,
          color: 'green',
        },
        {
          id: '5f7d4e6b-8a9c-4d0e-1f2a-3b4c5d6e7f8a',
          value: 'CONTACT_PLANNED',
          label: i18nLabel(msg`Contact Planned`),
          position: 3,
          color: 'teal',
        },
        {
          id: '6a8e5f7c-9b0d-4e1f-2a3b-4c5d6e7f8a9b',
          value: 'APPROACHED',
          label: i18nLabel(msg`Approached`),
          position: 4,
          color: 'cyan',
        },
        {
          id: '7b9f6a8d-0c1e-4f2a-3b4c-5d6e7f8a9b0c',
          value: 'NO_RESPONSE',
          label: i18nLabel(msg`No Response`),
          position: 5,
          color: 'yellow',
        },
        {
          id: '8c0a7b9e-1d2f-4a3b-4c5d-6e7f8a9b0c1d',
          value: 'DECLINED',
          label: i18nLabel(msg`Declined`),
          position: 6,
          color: 'red',
        },
        {
          id: '9d1b8c0f-2e3a-4b4c-5d6e-7f8a9b0c1d2e',
          value: 'INTERESTED',
          label: i18nLabel(msg`Interested`),
          position: 7,
          color: 'green',
        },
        {
          id: '0e2c9d1a-3f4b-4c5d-6e7f-8a9b0c1d2e3f',
          value: 'QUALIFYING',
          label: i18nLabel(msg`Qualifying`),
          position: 8,
          color: 'sky',
        },
        {
          id: '1f3d0e2b-4a5c-4d6e-7f8a-9b0c1d2e3f4a',
          value: 'QUALIFIED',
          label: i18nLabel(msg`Qualified`),
          position: 9,
          color: 'green',
        },
        {
          id: '2a4e1f3c-5b6d-4e7f-8a9b-0c1d2e3f4a5b',
          value: 'LONGLIST',
          label: i18nLabel(msg`Longlist`),
          position: 10,
          color: 'blue',
        },
        {
          id: '3b5f2a4d-6c7e-4f8a-9b0c-1d2e3f4a5b6c',
          value: 'CALIBRATION',
          label: i18nLabel(msg`Calibration`),
          position: 11,
          color: 'purple',
        },
        {
          id: '4c6a3b5e-7d8f-4a9b-0c1d-2e3f4a5b6c7d',
          value: 'PRESENTED',
          label: i18nLabel(msg`Presented`),
          position: 12,
          color: 'pink',
        },
        {
          id: '5d7b4c6f-8e0a-4b0c-1d2e-3f4a5b6c7d8e',
          value: 'CLIENT_HOLD',
          label: i18nLabel(msg`Client Hold`),
          position: 13,
          color: 'orange',
        },
        {
          id: '6e8c5d7a-9f1b-4c1d-2e3f-4a5b6c7d8e9f',
          value: 'SHORTLIST',
          label: i18nLabel(msg`Shortlist`),
          position: 14,
          color: 'blue',
        },
        {
          id: '7f9d6e8b-0a2c-4d2e-3f4a-5b6c7d8e9f0a',
          value: 'CLIENT_INTERVIEW',
          label: i18nLabel(msg`Client Interview`),
          position: 15,
          color: 'purple',
        },
        {
          id: '8a0e7f9c-1b3d-4e3f-4a5b-6c7d8e9f0a1b',
          value: 'FINALIST',
          label: i18nLabel(msg`Finalist`),
          position: 16,
          color: 'green',
        },
        {
          id: '9b1f8a0d-2c4e-4f4a-5b6c-7d8e9f0a1b2c',
          value: 'REFERENCES_STAGE',
          label: i18nLabel(msg`References Stage`),
          position: 17,
          color: 'teal',
        },
        {
          id: '0c2a9b1e-3d5f-4a5b-6c7d-8e9f0a1b2c3d',
          value: 'DILIGENCE',
          label: i18nLabel(msg`Diligence`),
          position: 18,
          color: 'sky',
        },
        {
          id: '1d3b0c2f-4e6a-4b6c-7d8e-9f0a1b2c3d4e',
          value: 'OFFER_NEGOTIATION',
          label: i18nLabel(msg`Offer Negotiation`),
          position: 19,
          color: 'yellow',
        },
        {
          id: '2e4c1d3a-5f7b-4c7d-8e9f-0a1b2c3d4e5f',
          value: 'PLACED',
          label: i18nLabel(msg`Placed`),
          position: 20,
          color: 'green',
        },
        {
          id: '3f5d2e4b-6a8c-4d8e-9f0a-1b2c3d4e5f6a',
          value: 'OFF_LIMITS',
          label: i18nLabel(msg`Off Limits`),
          position: 21,
          color: 'red',
        },
        {
          id: '4a6e3f5c-7b9d-4e9f-0a1b-2c3d4e5f6a7b',
          value: 'CONFLICT',
          label: i18nLabel(msg`Conflict`),
          position: 22,
          color: 'red',
        },
        {
          id: '5b7f4a6d-8c0e-4f0a-1b2c-3d4e5f6a7b8c',
          value: 'FUTURE_FIT',
          label: i18nLabel(msg`Future Fit`),
          position: 23,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  currentStage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'currentStage',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Current Stage`),
      description: i18nLabel(msg`Human-readable current stage`),
      icon: 'IconFlag',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  assignedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'assignedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Assigned At`),
      description: i18nLabel(msg`When the candidacy was assigned`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lastStageChangedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lastStageChangedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last Stage Changed At`),
      description: i18nLabel(msg`When the stage last changed`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  closedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'closedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Closed At`),
      description: i18nLabel(msg`When the candidacy was closed`),
      icon: 'IconCalendarClock',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  notes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'notes',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Notes`),
      description: i18nLabel(msg`Candidacy notes`),
      icon: 'IconFileText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidateConsentDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'candidateConsentDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Candidate Consent Date`),
      description: i18nLabel(msg`When consent was obtained`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignment: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'searchAssignment',
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchAssignment',
      targetFieldName: 'candidacies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'searchAssignmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment ID`),
      description: i18nLabel(msg`Associated search assignment ID`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  person: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'person',
      label: i18nLabel(msg`Person`),
      description: i18nLabel(msg`Linked person record`),
      icon: 'IconUserCircle',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'person',
      targetFieldName: 'candidacies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'personId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  personId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'personId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Person ID`),
      description: i18nLabel(msg`Linked person ID`),
      icon: 'IconUserCircle',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  researchCandidate: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'researchCandidate',
      label: i18nLabel(msg`Research Candidate`),
      description: i18nLabel(msg`Associated research candidate`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'researchCandidate',
      targetFieldName: 'candidacies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'researchCandidateId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  researchCandidateId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'researchCandidateId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Research Candidate ID`),
      description: i18nLabel(msg`Associated research candidate ID`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  executiveProfile: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'executiveProfile',
      label: i18nLabel(msg`Executive Profile`),
      description: i18nLabel(msg`Linked executive profile`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'executiveProfile',
      targetFieldName: 'candidacies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'executiveProfileId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  executiveProfileId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'executiveProfileId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Executive Profile ID`),
      description: i18nLabel(msg`Linked executive profile ID`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  stageEvents: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'stageEvents',
      label: i18nLabel(msg`Stage Events`),
      description: i18nLabel(msg`Stage transition events for this candidacy`),
      icon: 'IconProgress',
      isNullable: true,
      targetObjectName: 'candidacyStageEvent',
      targetFieldName: 'candidacy',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Search candidacy record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
