import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildResearchStrategyStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'researchStrategy', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'researchStrategy'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  owner: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'owner',
      label: i18nLabel(msg`Owner`),
      description: i18nLabel(msg`Owner of the research strategy`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'ownedResearchStrategies',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'ownerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  marketMaps: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'marketMaps',
      label: i18nLabel(msg`Market Maps`),
      description: i18nLabel(msg`Market maps for this strategy`),
      icon: 'IconMap',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'marketMap',
      targetFieldName: 'researchStrategy',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
        onDelete: RelationOnDeleteAction.CASCADE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  researchCandidates: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'researchCandidates',
      label: i18nLabel(msg`Research Candidates`),
      description: i18nLabel(msg`Research candidates for this strategy`),
      icon: 'IconUserSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'researchCandidate',
      targetFieldName: 'researchStrategy',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
        onDelete: RelationOnDeleteAction.CASCADE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Research strategy name`),
      icon: 'IconChartDots',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Research strategy status`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: '41184b57-9faf-4e63-b7ee-034af62991ba',
          value: 'DRAFT',
          label: i18nLabel(msg`Draft`),
          position: 0,
          color: 'gray',
        },
        {
          id: 'e2be9731-bb39-4f0d-8833-082910fe7307',
          value: 'IN_PROGRESS',
          label: i18nLabel(msg`In Progress`),
          position: 1,
          color: 'blue',
        },
        {
          id: '618c4bb4-4bd2-42f1-9179-dd79b5450b51',
          value: 'COMPLETED',
          label: i18nLabel(msg`Completed`),
          position: 2,
          color: 'green',
        },
        {
          id: 'd6906557-3424-428b-874b-cef7a0214bde',
          value: 'ARCHIVED',
          label: i18nLabel(msg`Archived`),
          position: 3,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  priority: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'priority',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Priority`),
      description: i18nLabel(msg`Research strategy priority`),
      icon: 'IconFlag',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'MEDIUM'",
      options: [
        {
          id: '27e8ef3e-7d19-46fc-835f-3f4ddb3eb11b',
          value: 'HIGH',
          label: i18nLabel(msg`High`),
          position: 0,
          color: 'red',
        },
        {
          id: 'cb8509d3-c1c1-4086-bdcc-d80d1a6a5e6e',
          value: 'MEDIUM',
          label: i18nLabel(msg`Medium`),
          position: 1,
          color: 'blue',
        },
        {
          id: '4e65b05a-058c-4107-b1b3-b74a35c978ca',
          value: 'LOW',
          label: i18nLabel(msg`Low`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  objectives: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'objectives',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Objectives`),
      description: i18nLabel(msg`Research strategy objectives`),
      icon: 'IconTarget',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetSegments: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'targetSegments',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Target Segments`),
      description: i18nLabel(msg`Target industries, functions, and geographies`),
      icon: 'IconHierarchy',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourcingChannels: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourcingChannels',
      type: FieldMetadataType.MULTI_SELECT,
      label: i18nLabel(msg`Sourcing Channels`),
      description: i18nLabel(msg`Channels used for sourcing`),
      icon: 'IconNetwork',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: '710634ef-4f1d-4df7-8c70-34322af05df3',
          value: 'DIRECT_OUTREACH',
          label: i18nLabel(msg`Direct Outreach`),
          position: 0,
          color: 'blue',
        },
        {
          id: '85e85dee-da44-441c-9653-63aea66ab517',
          value: 'REFERRAL',
          label: i18nLabel(msg`Referral`),
          position: 1,
          color: 'green',
        },
        {
          id: 'c49dc333-2944-4f4f-90cb-33142a8fbdea',
          value: 'NETWORK',
          label: i18nLabel(msg`Network`),
          position: 2,
          color: 'purple',
        },
        {
          id: 'bd1b5e5a-eec3-4847-b98b-3da0b9e9b17a',
          value: 'DATABASE',
          label: i18nLabel(msg`Database`),
          position: 3,
          color: 'orange',
        },
        {
          id: '5986254b-8d85-41ab-9618-9fd5262834c9',
          value: 'PARTNER',
          label: i18nLabel(msg`Partner`),
          position: 4,
          color: 'pink',
        },
        {
          id: '03eed283-339c-4ec6-8254-dc81f285c3e7',
          value: 'ENRICHMENT',
          label: i18nLabel(msg`Enrichment`),
          position: 5,
          color: 'yellow',
        },
        {
          id: '9ec32f7f-9157-4ce3-a544-f16cb1639745',
          value: 'OTHER',
          label: i18nLabel(msg`Other`),
          position: 6,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetCandidateCount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'targetCandidateCount',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Target Candidate Count`),
      description: i18nLabel(msg`Target number of candidates to identify`),
      icon: 'IconNumbers',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  startDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'startDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Start Date`),
      description: i18nLabel(msg`Research start date`),
      icon: 'IconCalendar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  targetCompletionDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'targetCompletionDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Target Completion Date`),
      description: i18nLabel(msg`Target date for completing research`),
      icon: 'IconCalendarDue',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  completedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'completedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Completed At`),
      description: i18nLabel(msg`When the research was completed`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Research strategy record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
