import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';

export const buildAnalyticsMetricSnapshotStandardFlatFieldMetadatas = ({ now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId, }: Omit<CreateStandardFieldArgs<'analyticsMetricSnapshot', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'analyticsMetricSnapshot'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid',},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Snapshot name`),icon:'IconUser',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  metricId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'metricId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Metric`),description:i18nLabel(msg`The metric definition this snapshot belongs to`),icon:'IconChartBar',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  metric: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'metric',type:FieldMetadataType.RELATION,label:i18nLabel(msg`Metric`),description:i18nLabel(msg`The metric definition this snapshot belongs to`),icon:'IconChartBar',isSystem:true,isNullable:false,isUIEditable:false,settings:{foreignKeyName:'metricId',},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  periodStart: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'periodStart',type:FieldMetadataType.DATE,label:i18nLabel(msg`Period Start`),description:i18nLabel(msg`Measurement window start date`),icon:'IconCalendar',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  periodEnd: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'periodEnd',type:FieldMetadataType.DATE,label:i18nLabel(msg`Period End`),description:i18nLabel(msg`Measurement window end date`),icon:'IconCalendar',isNullable:false,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  periodLabel: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'periodLabel',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Period Label`),description:i18nLabel(msg`Human-readable period (2026-Q2, 2026-07)`),icon:'IconCalendarDue',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  granularity: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'granularity',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Granularity`),description:i18nLabel(msg`Time granularity of the snapshot`),icon:'IconCalendarStats',isNullable:false,isUIEditable:true,defaultValue:"'MONTH'",options:[{id:'f0a1b2c3-s001-4000-8001-f0a1b2c3s001',value:'POINT_IN_TIME',label:i18nLabel(msg`Point In Time`),position:0,color:'blue',},{id:'f0a1b2c3-s002-4000-8001-f0a1b2c3s002',value:'DAY',label:i18nLabel(msg`Day`),position:1,color:'green',},{id:'f0a1b2c3-s003-4000-8001-f0a1b2c3s003',value:'WEEK',label:i18nLabel(msg`Week`),position:2,color:'orange',},{id:'f0a1b2c3-s004-4000-8001-f0a1b2c3s004',value:'MONTH',label:i18nLabel(msg`Month`),position:3,color:'purple',},{id:'f0a1b2c3-s005-4000-8001-f0a1b2c3s005',value:'QUARTER',label:i18nLabel(msg`Quarter`),position:4,color:'red',},{id:'f0a1b2c3-s006-4000-8001-f0a1b2c3s006',value:'YEAR',label:i18nLabel(msg`Year`),position:5,color:'yellow',},{id:'f0a1b2c3-s007-4000-8001-f0a1b2c3s007',value:'TRAILING_30D',label:i18nLabel(msg`Trailing 30 Days`),position:6,color:'turquoise',},{id:'f0a1b2c3-s008-4000-8001-f0a1b2c3s008',value:'TRAILING_90D',label:i18nLabel(msg`Trailing 90 Days`),position:7,color:'pink',},{id:'f0a1b2c3-s009-4000-8001-f0a1b2c3s009',value:'TRAILING_365D',label:i18nLabel(msg`Trailing 365 Days`),position:8,color:'grey',},{id:'f0a1b2c3-s010-4000-8001-f0a1b2c3s010',value:'LIFETIME',label:i18nLabel(msg`Lifetime`),position:9,color:'blue',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  value: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'value',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Value`),description:i18nLabel(msg`The numeric metric value`),icon:'IconNumber',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  valueText: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'valueText',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Value Text`),description:i18nLabel(msg`Formatted display value`),icon:'IconTypography',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  previousValue: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'previousValue',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Previous Value`),description:i18nLabel(msg`Prior period value for trend calculation`),icon:'IconArrowBackUp',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  delta: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'delta',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Delta`),description:i18nLabel(msg`Absolute change from previous period`),icon:'IconDelta',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  deltaPercent: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deltaPercent',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Delta Percent`),description:i18nLabel(msg`Percentage change from previous period`),icon:'IconPercentage',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  targetValue: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'targetValue',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Target Value`),description:i18nLabel(msg`Goal or benchmark value for comparison`),icon:'IconTarget',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  dimensions: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'dimensions',type:FieldMetadataType.JSON,label:i18nLabel(msg`Dimensions`),description:i18nLabel(msg`Dimension breakdown e.g. practiceGroup, clientCompanyId`),icon:'IconDimensions',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  sourceCount: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'sourceCount',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Source Count`),description:i18nLabel(msg`Number of underlying domain records aggregated`),icon:'IconSum',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  computedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'computedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Computed At`),description:i18nLabel(msg`When this snapshot was produced`),icon:'IconClock',isNullable:false,isUIEditable:true,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  computationStatus: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'computationStatus',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Computation Status`),description:i18nLabel(msg`Status of the computation that produced this snapshot`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'SUCCESS'",options:[{id:'f0a1b2c3-s101-4000-8001-f0a1b2c3s101',value:'SUCCESS',label:i18nLabel(msg`Success`),position:0,color:'green',},{id:'f0a1b2c3-s102-4000-8001-f0a1b2c3s102',value:'PARTIAL',label:i18nLabel(msg`Partial`),position:1,color:'orange',},{id:'f0a1b2c3-s103-4000-8001-f0a1b2c3s103',value:'FAILED',label:i18nLabel(msg`Failed`),position:2,color:'red',},{id:'f0a1b2c3-s104-4000-8001-f0a1b2c3s104',value:'STALE',label:i18nLabel(msg`Stale`),position:3,color:'grey',},],},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  computationNotes: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'computationNotes',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Computation Notes`),description:i18nLabel(msg`Error details or staleness reason`),icon:'IconNotes',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  computedById: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'computedById',type:FieldMetadataType.UUID,label:i18nLabel(msg`Computed By`),description:i18nLabel(msg`User who triggered the computation (manual); system jobs leave null`),icon:'IconUser',isNullable:true,isUIEditable:true,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  computedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'computedBy',type:FieldMetadataType.RELATION,label:i18nLabel(msg`Computed By`),description:i18nLabel(msg`User who triggered the computation`),icon:'IconUser',isSystem:true,isNullable:true,isUIEditable:false,settings:{foreignKeyName:'computedById',},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`Creator`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`Last updater`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null,},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:{position:'first'},},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
  searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Search Vector`),description:i18nLabel(msg`Search vector for full-text search`),icon:'IconSearch',isSystem:true,isNullable:true,isUIEditable:false,},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now,}),
});
