import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildExecutiveAssessmentStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'executiveAssessment', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'executiveAssessment'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Assessment name`),
      icon: 'IconUser',
      isNullable: false,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Assessment status`),
      icon: 'IconProgress',
      isNullable: false,
      isUIEditable: true,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0001001',
          value: 'DRAFT',
          label: i18nLabel(msg`Draft`),
          position: 0,
          color: 'gray',
        },
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0001002',
          value: 'IN_PROGRESS',
          label: i18nLabel(msg`In Progress`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0001003',
          value: 'COMPLETE',
          label: i18nLabel(msg`Complete`),
          position: 2,
          color: 'green',
        },
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0001004',
          value: 'REVIEWED',
          label: i18nLabel(msg`Reviewed`),
          position: 3,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  overallAssessment: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'overallAssessment',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Overall Assessment`),
      description: i18nLabel(msg`Overall assessment summary`),
      icon: 'IconClipboardText',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  strengthsSummary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'strengthsSummary',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Strengths Summary`),
      description: i18nLabel(msg`Summary of candidate strengths`),
      icon: 'IconTrendingUp',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  riskFactorsSummary: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'riskFactorsSummary',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Risk Factors Summary`),
      description: i18nLabel(msg`Summary of risk factors and concerns`),
      icon: 'IconAlertTriangle',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  recommendation: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'recommendation',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Recommendation`),
      description: i18nLabel(msg`Assessment recommendation`),
      icon: 'IconThumbUp',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0002001',
          value: 'STRONG_APPROVE',
          label: i18nLabel(msg`Strong Approve`),
          position: 0,
          color: 'green',
        },
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0002002',
          value: 'APPROVE',
          label: i18nLabel(msg`Approve`),
          position: 1,
          color: 'teal',
        },
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0002003',
          value: 'NEUTRAL',
          label: i18nLabel(msg`Neutral`),
          position: 2,
          color: 'yellow',
        },
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0002004',
          value: 'CAUTION',
          label: i18nLabel(msg`Caution`),
          position: 3,
          color: 'orange',
        },
        {
          id: 'aeb1a001-0060-4000-8001-aeb1a0002005',
          value: 'DO_NOT_PROCEED',
          label: i18nLabel(msg`Do Not Proceed`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  assessmentDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'assessmentDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Assessment Date`),
      description: i18nLabel(msg`Date when the assessment was performed`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      isUIEditable: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  assessor: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'assessor',
      label: i18nLabel(msg`Assessor`),
      description: i18nLabel(msg`Person who performed the assessment`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'executiveAssessments',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'assessorId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  assessorId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'assessorId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Assessor ID`),
      description: i18nLabel(msg`Assessor ID`),
      icon: 'IconUserCheck',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacy: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'candidacy',
      label: i18nLabel(msg`Candidacy`),
      description: i18nLabel(msg`Associated candidacy`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchCandidacy',
      targetFieldName: 'executiveAssessments',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'candidacyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  candidacyId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'candidacyId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Candidacy ID`),
      description: i18nLabel(msg`Associated candidacy ID`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignment: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'searchAssignment',
      label: i18nLabel(msg`Search Assignment`),
      description: i18nLabel(msg`Associated search assignment`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'searchAssignment',
      targetFieldName: 'executiveAssessments',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'searchAssignmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchAssignmentId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchAssignmentId',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Search Assignment ID`),
      description: i18nLabel(msg`Associated search assignment ID`),
      icon: 'IconSearch',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  consentToShare: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'consentToShare',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Consent to Share`),
      description: i18nLabel(msg`Whether consent was given to share with client`),
      icon: 'IconShare',
      isNullable: true,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isClientVisible: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isClientVisible',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Client Visible`),
      description: i18nLabel(msg`Whether this assessment is visible to client`),
      icon: 'IconEye',
      isNullable: true,
      isUIEditable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  evaluations: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'evaluations',
      label: i18nLabel(msg`Evaluations`),
      description: i18nLabel(msg`Criterion evaluations in this assessment`),
      icon: 'IconChecklist',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'criterionEvaluation',
      targetFieldName: 'assessment',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
        onDelete: RelationOnDeleteAction.CASCADE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
