import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import { DateDisplayFormat, FieldMetadataType, RelationOnDeleteAction, RelationType } from 'twenty-shared/types';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { type CreateStandardFieldArgs, createStandardFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildSearchInterviewStandardFlatFieldMetadatas = ({
  now, objectName, workspaceId, standardObjectMetadataRelatedEntityIds, dependencyFlatEntityMaps, twentyStandardApplicationId,
}: Omit<CreateStandardFieldArgs<'searchInterview', FieldMetadataType>, 'context'>): Record<AllStandardObjectFieldName<'searchInterview'>, FlatFieldMetadata> => ({
id: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'id',type:FieldMetadataType.UUID,label:i18nLabel(msg`Id`),description:i18nLabel(msg`Id`),icon:'Icon123',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'uuid'},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
createdAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Creation date`),description:i18nLabel(msg`Creation date`),icon:'IconCalendar',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
updatedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Last update`),description:i18nLabel(msg`Last time the record was changed`),icon:'IconCalendarClock',isSystem:true,isNullable:false,isUIEditable:false,defaultValue:'now',settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
deletedAt: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'deletedAt',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Deleted at`),description:i18nLabel(msg`Date when the record was deleted`),icon:'IconCalendarMinus',isSystem:true,isNullable:true,isUIEditable:false,settings:{displayFormat:DateDisplayFormat.RELATIVE}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchAssignmentId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchAssignmentId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Search Assignment`),description:i18nLabel(msg`Associated search assignment`),icon:'IconSearch',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchAssignment: createStandardRelationFieldFlatMetadata({objectName,workspaceId,context:{type:FieldMetadataType.RELATION,morphId:null,fieldName:'searchAssignment',label:i18nLabel(msg`Search Assignment`),description:i18nLabel(msg`Search assignment this interview belongs to`),icon:'IconSearch',isNullable:true,isUIEditable:true,targetObjectName:'searchAssignment',targetFieldName:'interviews',settings:{relationType:RelationType.MANY_TO_ONE,onDelete:RelationOnDeleteAction.SET_NULL,joinColumnName:'searchAssignmentId'}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchCandidacyId: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchCandidacyId',type:FieldMetadataType.UUID,label:i18nLabel(msg`Search Candidacy`),description:i18nLabel(msg`Associated search candidacy`),icon:'IconUser',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchCandidacy: createStandardRelationFieldFlatMetadata({objectName,workspaceId,context:{type:FieldMetadataType.RELATION,morphId:null,fieldName:'searchCandidacy',label:i18nLabel(msg`Search Candidacy`),description:i18nLabel(msg`Candidacy this interview is for`),icon:'IconUser',isNullable:true,isUIEditable:true,targetObjectName:'searchCandidacy',targetFieldName:'interviews',settings:{relationType:RelationType.MANY_TO_ONE,onDelete:RelationOnDeleteAction.SET_NULL,joinColumnName:'searchCandidacyId'}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
name: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'name',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Name`),description:i18nLabel(msg`Interview name`),icon:'IconFileDescription',isNullable:false,isUIEditable:true,defaultValue:"'New Interview'"},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
interviewType: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'interviewType',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Interview Type`),description:i18nLabel(msg`Type of interview`),icon:'IconVideo',isNullable:false,isUIEditable:true,defaultValue:"'PHONE_SCREEN'",options:[{id:'aeb1d000-2001-4000-8000-000000000001',value:'PHONE_SCREEN',label:i18nLabel(msg`Phone Screen`),position:0,color:'blue'},{id:'aeb1d000-2001-4000-8000-000000000002',value:'VIDEO',label:i18nLabel(msg`Video`),position:1,color:'turquoise'},{id:'aeb1d000-2001-4000-8000-000000000003',value:'IN_PERSON',label:i18nLabel(msg`In Person`),position:2,color:'green'},{id:'aeb1d000-2001-4000-8000-000000000004',value:'PANEL',label:i18nLabel(msg`Panel`),position:3,color:'purple'},{id:'aeb1d000-2001-4000-8000-000000000005',value:'ASSESSMENT_DAY',label:i18nLabel(msg`Assessment Day`),position:4,color:'yellow'},{id:'aeb1d000-2001-4000-8000-000000000006',value:'TECHNICAL_DEEP_DIVE',label:i18nLabel(msg`Technical Deep Dive`),position:5,color:'red'},{id:'aeb1d000-2001-4000-8000-000000000007',value:'CASE_PRESENTATION',label:i18nLabel(msg`Case Presentation`),position:6,color:'pink'},{id:'aeb1d000-2001-4000-8000-000000000008',value:'FINAL_ROUND',label:i18nLabel(msg`Final Round`),position:7,color:'orange'},{id:'aeb1d000-2001-4000-8000-000000000009',value:'OTHER',label:i18nLabel(msg`Other`),position:8,color:'gray'},]},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
status: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'status',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Status`),description:i18nLabel(msg`Interview status`),icon:'IconStatusChange',isNullable:false,isUIEditable:true,defaultValue:"'SCHEDULED'",options:[{id:'aeb1d000-2010-4000-8000-000000000001',value:'PROPOSED',label:i18nLabel(msg`Proposed`),position:0,color:'gray'},{id:'aeb1d000-2010-4000-8000-000000000002',value:'SCHEDULED',label:i18nLabel(msg`Scheduled`),position:1,color:'blue'},{id:'aeb1d000-2010-4000-8000-000000000003',value:'CONFIRMED',label:i18nLabel(msg`Confirmed`),position:2,color:'green'},{id:'aeb1d000-2010-4000-8000-000000000004',value:'IN_PROGRESS',label:i18nLabel(msg`In Progress`),position:3,color:'yellow'},{id:'aeb1d000-2010-4000-8000-000000000005',value:'COMPLETED',label:i18nLabel(msg`Completed`),position:4,color:'purple'},{id:'aeb1d000-2010-4000-8000-000000000006',value:'CANCELLED',label:i18nLabel(msg`Cancelled`),position:5,color:'red'},{id:'aeb1d000-2010-4000-8000-000000000007',value:'RESCHEDULED',label:i18nLabel(msg`Rescheduled`),position:6,color:'orange'},]},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
scheduledDate: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'scheduledDate',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Scheduled Date`),description:i18nLabel(msg`When the interview is scheduled`),icon:'IconCalendar',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
scheduledEndDate: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'scheduledEndDate',type:FieldMetadataType.DATE_TIME,label:i18nLabel(msg`Scheduled End Date`),description:i18nLabel(msg`When the interview is expected to end`),icon:'IconCalendar',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
duration: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'duration',type:FieldMetadataType.NUMBER,label:i18nLabel(msg`Duration (minutes)`),description:i18nLabel(msg`Interview duration in minutes`),icon:'IconClock',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
location: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'location',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Location`),description:i18nLabel(msg`Physical location for the interview`),icon:'IconMapPin',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
notes: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'notes',type:FieldMetadataType.RICH_TEXT,label:i18nLabel(msg`Notes`),description:i18nLabel(msg`Interview notes`),icon:'IconFileText',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
outcome: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'outcome',type:FieldMetadataType.SELECT,label:i18nLabel(msg`Outcome`),description:i18nLabel(msg`Interview outcome`),icon:'IconCheck',isNullable:true,isUIEditable:true,options:[{id:'aeb1d000-2017-4000-8000-000000000001',value:'ADVANCE_HIRE',label:i18nLabel(msg`Advance \u2014 Hire`),position:0,color:'green'},{id:'aeb1d000-2017-4000-8000-000000000002',value:'ADVANCE_LEAN_HIRE',label:i18nLabel(msg`Advance \u2014 Lean Hire`),position:1,color:'turquoise'},{id:'aeb1d000-2017-4000-8000-000000000003',value:'HOLD_NO_CONSENSUS',label:i18nLabel(msg`Hold \u2014 No Consensus`),position:2,color:'yellow'},{id:'aeb1d000-2017-4000-8000-000000000004',value:'REJECT_LEAN_PASS',label:i18nLabel(msg`Reject \u2014 Lean Pass`),position:3,color:'red'},{id:'aeb1d000-2017-4000-8000-000000000005',value:'REJECT_PASS',label:i18nLabel(msg`Reject \u2014 Pass`),position:4,color:'red'},]},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
internalNotes: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'internalNotes',type:FieldMetadataType.RICH_TEXT,label:i18nLabel(msg`Internal Notes`),description:i18nLabel(msg`Internal notes about the interview`),icon:'IconFileText',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
interviewers: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'interviewers',type:FieldMetadataType.TEXT,label:i18nLabel(msg`Interviewers`),description:i18nLabel(msg`Interviewer names or references`),icon:'IconUsers',isNullable:true,isUIEditable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
clientFeedbacks: createStandardRelationFieldFlatMetadata({objectName,workspaceId,context:{type:FieldMetadataType.RELATION,morphId:null,fieldName:'clientFeedbacks',label:i18nLabel(msg`Client Feedbacks`),description:i18nLabel(msg`Client feedback on this interview`),icon:'IconMessages',isNullable:true,isUIEditable:true,targetObjectName:'clientFeedback',targetFieldName:'searchInterview',settings:{relationType:RelationType.ONE_TO_MANY,onDelete:RelationOnDeleteAction.SET_NULL}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
createdBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'createdBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Created by`),description:i18nLabel(msg`The creator of the record`),icon:'IconCreativeCommonsSa',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
updatedBy: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'updatedBy',type:FieldMetadataType.ACTOR,label:i18nLabel(msg`Updated by`),description:i18nLabel(msg`The workspace member who last updated the record`),icon:'IconUserCircle',isSystem:true,isUIEditable:false,isNullable:false,defaultValue:{source:"'MANUAL'",name:"'System'",workspaceMemberId:null}},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
position: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'position',type:FieldMetadataType.POSITION,label:i18nLabel(msg`Position`),description:i18nLabel(msg`Search interview record position`),icon:'IconHierarchy2',isSystem:true,isNullable:false,defaultValue:0},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
searchVector: createStandardFieldFlatMetadata({objectName,workspaceId,context:{fieldName:'searchVector',type:FieldMetadataType.TS_VECTOR,label:i18nLabel(msg`Search vector`),description:i18nLabel(msg`Field used for full-text search`),icon:'IconUser',isSystem:true,isNullable:true},standardObjectMetadataRelatedEntityIds,dependencyFlatEntityMaps,twentyStandardApplicationId,now}),
});
