export enum AiCapability {
  ASSIGNMENT_INTAKE = 'ASSIGNMENT_INTAKE',
  POSITION_SPEC = 'POSITION_SPEC',
  RESEARCH_STRATEGY = 'RESEARCH_STRATEGY',
  STATUS_REPORT = 'STATUS_REPORT',
  CANDIDATE_PRESENTATION = 'CANDIDATE_PRESENTATION',
  NATURAL_LANGUAGE_SEARCH = 'NATURAL_LANGUAGE_SEARCH',
  TARGET_COMPANY_SUGGESTION = 'TARGET_COMPANY_SUGGESTION',
  RELATIONSHIP_PATH_SUGGESTION = 'RELATIONSHIP_PATH_SUGGESTION',
  CRITERION_ASSESSMENT = 'CRITERION_ASSESSMENT',
  BOARD_MATRIX_EVALUATION = 'BOARD_MATRIX_EVALUATION',
  SEARCH_HEALTH_ADVISORY = 'SEARCH_HEALTH_ADVISORY',
}
