export enum AiPromptCategory {
  ASSIGNMENT_INTAKE = 'ASSIGNMENT_INTAKE',
  POSITION_SPEC = 'POSITION_SPEC',
  RESEARCH_STRATEGY = 'RESEARCH_STRATEGY',
  STATUS_REPORT = 'STATUS_REPORT',
  CANDIDATE_PRESENTATION = 'CANDIDATE_PRESENTATION',
  CRITERION_ASSESSMENT = 'CRITERION_ASSESSMENT',
  BOARD_MATRIX = 'BOARD_MATRIX',
  SEARCH_HEALTH = 'SEARCH_HEALTH',
}
