export enum AnalyticsTimeWindow {
  POINT_IN_TIME = 'POINT_IN_TIME',
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  QUARTER = 'QUARTER',
  YEAR = 'YEAR',
  TRAILING_30D = 'TRAILING_30D',
  TRAILING_90D = 'TRAILING_90D',
  TRAILING_365D = 'TRAILING_365D',
  LIFETIME = 'LIFETIME',
}
