export enum AnalyticsDashboardAudience {
  MANAGING_PARTNER = 'MANAGING_PARTNER',
  PRACTICE_LEADER = 'PRACTICE_LEADER',
  FINANCE_OPS = 'FINANCE_OPS',
  SEARCH_PARTNER = 'SEARCH_PARTNER',
  ALL_INTERNAL = 'ALL_INTERNAL',
}
