export enum AppAgentCapability {
  ASSIGNMENT_INTAKE = 'ASSIGNMENT_INTAKE',
  POSITION_SPECIFICATION_DRAFT = 'POSITION_SPECIFICATION_DRAFT',
  RESEARCH_STRATEGY_DRAFT = 'RESEARCH_STRATEGY_DRAFT',
  STATUS_REPORT_DRAFT = 'STATUS_REPORT_DRAFT',
  CANDIDATE_PRESENTATION_DRAFT = 'CANDIDATE_PRESENTATION_DRAFT',
  NL_SEARCH_FILTERS = 'NL_SEARCH_FILTERS',
  TARGET_COMPANY_SUGGEST = 'TARGET_COMPANY_SUGGEST',
  RELATIONSHIP_PATH_SUGGEST = 'RELATIONSHIP_PATH_SUGGEST',
  CRITERION_ASSESSMENT_SHADOW = 'CRITERION_ASSESSMENT_SHADOW',
  BOARD_MATRIX_EVALUATION = 'BOARD_MATRIX_EVALUATION',
  SEARCH_HEALTH_ADVISORY = 'SEARCH_HEALTH_ADVISORY',
}
