export enum BoardMatrixCriterionCategory {
  GOVERNANCE = 'GOVERNANCE',
  FINANCIAL_EXPERTISE = 'FINANCIAL_EXPERTISE',
  INDUSTRY_KNOWLEDGE = 'INDUSTRY_KNOWLEDGE',
  TECHNOLOGY = 'TECHNOLOGY',
  INTERNATIONAL = 'INTERNATIONAL',
  DIVERSITY = 'DIVERSITY',
  INDEPENDENCE = 'INDEPENDENCE',
  CEO_EXPERIENCE = 'CEO_EXPERIENCE',
  OPERATIONAL = 'OPERATIONAL',
  OTHER = 'OTHER',
}
