export enum BoardCommitmentReviewStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ACCEPTABLE_LOAD = 'ACCEPTABLE_LOAD',
  HIGH_LOAD = 'HIGH_LOAD',
  EXCESSIVE_LOAD = 'EXCESSIVE_LOAD',
  CONFLICT_FOUND = 'CONFLICT_FOUND',
}
