export enum BoardCompositionTargetBoardType {
  PUBLIC_FOR_PROFIT = 'PUBLIC_FOR_PROFIT',
  PRIVATE_FOR_PROFIT = 'PRIVATE_FOR_PROFIT',
  NON_PROFIT = 'NON_PROFIT',
  ADVISORY = 'ADVISORY',
  PRIVATE_EQUITY_PORTFOLIO = 'PRIVATE_EQUITY_PORTFOLIO',
}
