export enum ConflictCheckOutcome {
  CLEAR = 'CLEAR',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  BLOCKED = 'BLOCKED',
  WAIVER_REQUIRED = 'WAIVER_REQUIRED',
  EXPIRED_REVIEW_REQUIRED = 'EXPIRED_REVIEW_REQUIRED',
}
