export enum ConfidentialityRecordType {
  NDA = 'NDA',
  CONFIDENTIALITY_ACKNOWLEDGMENT = 'CONFIDENTIALITY_ACKNOWLEDGMENT',
  SEARCH_CONFIDENTIALITY = 'SEARCH_CONFIDENTIALITY',
  MUTUAL_NDA = 'MUTUAL_NDA',
}
