export enum DiligenceCheckType {
  BACKGROUND_CHECK = 'BACKGROUND_CHECK',
  CREDENTIAL_VERIFICATION = 'CREDENTIAL_VERIFICATION',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  REGULATORY = 'REGULATORY',
  LEGAL = 'LEGAL',
  CONFLICT_OF_INTEREST = 'CONFLICT_OF_INTEREST',
  OTHER = 'OTHER',
}
