export enum DiligenceCheckStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_THIRD_PARTY = 'PENDING_THIRD_PARTY',
  COMPLETED_CLEAR = 'COMPLETED_CLEAR',
  COMPLETED_FLAGGED = 'COMPLETED_FLAGGED',
}
