export enum DirectorIndependenceReviewStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  INDEPENDENT = 'INDEPENDENT',
  NON_INDEPENDENT = 'NON_INDEPENDENT',
  QUALIFIED_INDEPENDENCE = 'QUALIFIED_INDEPENDENCE',
  FURTHER_REVIEW = 'FURTHER_REVIEW',
}
