export enum OffLimitsBasis {
  CLIENT_AGREEMENT = 'CLIENT_AGREEMENT',
  FIRM_POLICY = 'FIRM_POLICY',
  CANDIDATE_REQUEST = 'CANDIDATE_REQUEST',
  LEGAL = 'LEGAL',
  PRIOR_PLACEMENT = 'PRIOR_PLACEMENT',
}
