export enum OffLimitsType {
  OFF_LIMITS = 'OFF_LIMITS',
  DO_NOT_CONTACT = 'DO_NOT_CONTACT',
  NO_POACH = 'NO_POACH',
  EXCLUSIVE_CLIENT = 'EXCLUSIVE_CLIENT',
  TALENT_MAPPING_ONLY = 'TALENT_MAPPING_ONLY',
}
