export enum RelationshipType {
  COLLEAGUE = 'COLLEAGUE',
  MANAGER_REPORT = 'MANAGER_REPORT',
  MENTOR_MENTEE = 'MENTOR_MENTEE',
  CLIENT = 'CLIENT',
  VENDOR = 'VENDOR',
  INVESTOR = 'INVESTOR',
  BOARD_COLLEAGUE = 'BOARD_COLLEAGUE',
  REFERENCE = 'REFERENCE',
  REFERRAL_SOURCE = 'REFERRAL_SOURCE',
  ALUMNUS = 'ALUMNUS',
  OTHER = 'OTHER',
}
