export enum ResearchCandidateStatus {
  IDENTIFIED = 'IDENTIFIED',
  RESEARCHING = 'RESEARCHING',
  RESEARCHED = 'RESEARCHED',
  NOT_A_FIT = 'NOT_A_FIT',
  DUPLICATE = 'DUPLICATE',
  CONVERTED = 'CONVERTED',
}
