export enum SearchCriterionCategory {
  EXPERIENCE = 'EXPERIENCE',
  EDUCATION = 'EDUCATION',
  COMPETENCY = 'COMPETENCY',
  INDUSTRY = 'INDUSTRY',
  LEADERSHIP = 'LEADERSHIP',
  CULTURE_FIT = 'CULTURE_FIT',
  OTHER = 'OTHER',
}
