export enum SearchInterviewOutcome {
  ADVANCE_HIRE = 'ADVANCE_HIRE',
  ADVANCE_LEAN_HIRE = 'ADVANCE_LEAN_HIRE',
  HOLD_NO_CONSENSUS = 'HOLD_NO_CONSENSUS',
  REJECT_LEAN_PASS = 'REJECT_LEAN_PASS',
  REJECT_PASS = 'REJECT_PASS',
}
