export enum SearchInterviewType {
  PHONE_SCREEN = 'PHONE_SCREEN',
  VIDEO = 'VIDEO',
  IN_PERSON = 'IN_PERSON',
  PANEL = 'PANEL',
  ASSESSMENT_DAY = 'ASSESSMENT_DAY',
  TECHNICAL_DEEP_DIVE = 'TECHNICAL_DEEP_DIVE',
  CASE_PRESENTATION = 'CASE_PRESENTATION',
  FINAL_ROUND = 'FINAL_ROUND',
  OTHER = 'OTHER',
}
