export enum SourcingChannel {
  DIRECT_OUTREACH = 'DIRECT_OUTREACH',
  REFERRAL = 'REFERRAL',
  NETWORK = 'NETWORK',
  DATABASE = 'DATABASE',
  PARTNER = 'PARTNER',
  ENRICHMENT = 'ENRICHMENT',
  OTHER = 'OTHER',
}
