import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';
import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { type CreateStandardViewFieldArgs, createStandardViewFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardAnalyticsDomainMetricViewFields = ({ context, }: Omit<CreateStandardViewFieldArgs<'analyticsDomainMetric'>, 'context'>): Record<string, FlatViewField> => ({
  name: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'name', fieldName: 'name', position: 0, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  code: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'code', fieldName: 'code', position: 1, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  category: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'category', fieldName: 'category', position: 2, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  aggregationType: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'aggregationType', fieldName: 'aggregationType', position: 3, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  valueType: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'valueType', fieldName: 'valueType', position: 4, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  timeWindow: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'timeWindow', fieldName: 'timeWindow', position: 5, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  sourceObject: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'sourceObject', fieldName: 'sourceObject', position: 6, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  status: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'status', fieldName: 'status', position: 7, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  isConfidential: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'isConfidential', fieldName: 'isConfidential', position: 8, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  ownerWorkspaceMember: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'ownerWorkspaceMember', fieldName: 'ownerWorkspaceMember', position: 9, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  createdAt: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'createdAt', fieldName: 'createdAt', position: 10, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
  createdBy: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDomainMetric' as AllStandardObjectName, context: { viewName: 'analyticsDomainMetricRecordPageFields', viewFieldName: 'createdBy', fieldName: 'createdBy', position: 11, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
});
