import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';
import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { type CreateStandardViewFieldArgs, createStandardViewFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardAnalyticsDashboardConfigViewFields = ({ context, }: Omit<CreateStandardViewFieldArgs<'analyticsDashboardConfig'>, 'context'>): Record<string, FlatViewField> => ({
  name: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'name', fieldName: 'name', position: 0, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  scope: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'scope', fieldName: 'scope', position: 1, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  audience: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'audience', fieldName: 'audience', position: 2, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  defaultTimeRange: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'defaultTimeRange', fieldName: 'defaultTimeRange', position: 3, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  refreshFrequency: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'refreshFrequency', fieldName: 'refreshFrequency', position: 4, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  isShared: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'isShared', fieldName: 'isShared', position: 5, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  status: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'status', fieldName: 'status', position: 6, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  ownerWorkspaceMember: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'ownerWorkspaceMember', fieldName: 'ownerWorkspaceMember', position: 7, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  createdAt: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'createdAt', fieldName: 'createdAt', position: 8, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
  createdBy: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsDashboardConfig' as AllStandardObjectName, context: { viewName: 'analyticsDashboardConfigRecordPageFields', viewFieldName: 'createdBy', fieldName: 'createdBy', position: 9, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
});
