import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';
import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { type CreateStandardViewFieldArgs, createStandardViewFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardBoardMatrixCriterionViewFields = ({ context, }: Omit<CreateStandardViewFieldArgs<'boardMatrixCriterion'>, 'context'>): Record<string, FlatViewField> => ({
  name: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'name', fieldName: 'name', position: 0, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  category: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'category', fieldName: 'category', position: 1, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  weight: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'weight', fieldName: 'weight', position: 2, isVisible: true, size: 100, viewFieldGroupName: 'general', }, }, context, }),
  description: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'description', fieldName: 'description', position: 3, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  isRequired: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'isRequired', fieldName: 'isRequired', position: 4, isVisible: true, size: 100, viewFieldGroupName: 'general', }, }, context, }),
  boardCompositionProfile: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'boardCompositionProfile', fieldName: 'boardCompositionProfile', position: 5, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  createdAt: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'createdAt', fieldName: 'createdAt', position: 6, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
  createdBy: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardMatrixCriterion' as AllStandardObjectName, context: { viewName: 'boardMatrixCriterionRecordPageFields', viewFieldName: 'createdBy', fieldName: 'createdBy', position: 7, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
});
