import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { createStandardViewFieldFlatMetadata, type CreateStandardViewFieldArgs } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardOfferNegotiationViewFields = (args: Omit<CreateStandardViewFieldArgs<'offerNegotiation'>, 'context'>): Record<string, FlatViewField> => ({
offerNegotiationRecordPageFieldsName: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'name',fieldName:'name',position:0,isVisible:true,size:200,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'status',fieldName:'status',position:1,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsOfferAmount: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'offerAmount',fieldName:'offerAmount',position:2,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsCurrencyCode: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'currencyCode',fieldName:'currencyCode',position:3,isVisible:true,size:100,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsEquityTerms: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'equityTerms',fieldName:'equityTerms',position:4,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsBonusTerms: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'bonusTerms',fieldName:'bonusTerms',position:5,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsProposedStartDate: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'proposedStartDate',fieldName:'proposedStartDate',position:6,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsAcceptedSalary: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'acceptedSalary',fieldName:'acceptedSalary',position:7,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsAcceptedTotalCompensation: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'acceptedTotalCompensation',fieldName:'acceptedTotalCompensation',position:8,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsCandidacy: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'candidacy',fieldName:'candidacy',position:9,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsSearchAssignment: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'searchAssignment',fieldName:'searchAssignment',position:10,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsCompensationExpectation: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'compensationExpectation',fieldName:'compensationExpectation',position:11,isVisible:true,size:150,viewFieldGroupName:'general'}}),
offerNegotiationRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'createdAt',fieldName:'createdAt',position:12,isVisible:true,size:150,viewFieldGroupName:'system'}}),
offerNegotiationRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({...args,objectName:'offerNegotiation',context:{viewName:'offerNegotiationRecordPageFields',viewFieldName:'createdBy',fieldName:'createdBy',position:13,isVisible:true,size:150,viewFieldGroupName:'system'}}),
});
