import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { createStandardViewFieldFlatMetadata, type CreateStandardViewFieldArgs } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardPlacementViewFields = (args: Omit<CreateStandardViewFieldArgs<'placement'>, 'context'>): Record<string, FlatViewField> => ({
placementRecordPageFieldsName: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'name',fieldName:'name',position:0,isVisible:true,size:200,viewFieldGroupName:'general'}}),
placementRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'status',fieldName:'status',position:1,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsPlacementDate: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'placementDate',fieldName:'placementDate',position:2,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsStartDate: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'startDate',fieldName:'startDate',position:3,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsFeeAmount: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'feeAmount',fieldName:'feeAmount',position:4,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsFeeCurrencyCode: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'feeCurrencyCode',fieldName:'feeCurrencyCode',position:5,isVisible:true,size:100,viewFieldGroupName:'general'}}),
placementRecordPageFieldsInvoiceReference: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'invoiceReference',fieldName:'invoiceReference',position:6,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsGuaranteePeriodMonths: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'guaranteePeriodMonths',fieldName:'guaranteePeriodMonths',position:7,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsGuaranteeEndDate: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'guaranteeEndDate',fieldName:'guaranteeEndDate',position:8,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsBillingContact: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'billingContact',fieldName:'billingContact',position:9,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsCandidacy: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'candidacy',fieldName:'candidacy',position:10,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsOfferNegotiation: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'offerNegotiation',fieldName:'offerNegotiation',position:11,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsSearchAssignment: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'searchAssignment',fieldName:'searchAssignment',position:12,isVisible:true,size:150,viewFieldGroupName:'general'}}),
placementRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'createdAt',fieldName:'createdAt',position:13,isVisible:true,size:150,viewFieldGroupName:'system'}}),
placementRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({...args,objectName:'placement',context:{viewName:'placementRecordPageFields',viewFieldName:'createdBy',fieldName:'createdBy',position:14,isVisible:true,size:150,viewFieldGroupName:'system'}}),
});
