import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { createStandardViewFieldFlatMetadata, type CreateStandardViewFieldArgs } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardCompensationExpectationViewFields = (args: Omit<CreateStandardViewFieldArgs<'compensationExpectation'>, 'context'>): Record<string, FlatViewField> => ({
compensationExpectationRecordPageFieldsName: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'name',fieldName:'name',position:0,isVisible:true,size:200,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsExpectedBaseSalary: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'expectedBaseSalary',fieldName:'expectedBaseSalary',position:1,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsExpectedTotalCompensation: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'expectedTotalCompensation',fieldName:'expectedTotalCompensation',position:2,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsExpectedEquity: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'expectedEquity',fieldName:'expectedEquity',position:3,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsExpectedBonus: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'expectedBonus',fieldName:'expectedBonus',position:4,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsCurrencyCode: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'currencyCode',fieldName:'currencyCode',position:5,isVisible:true,size:100,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsExpectationSource: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'expectationSource',fieldName:'expectationSource',position:6,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsIsVerifiedWithCandidate: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'isVerifiedWithCandidate',fieldName:'isVerifiedWithCandidate',position:7,isVisible:true,size:100,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsVerifiedAt: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'verifiedAt',fieldName:'verifiedAt',position:8,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsCandidacy: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'candidacy',fieldName:'candidacy',position:9,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsSearchAssignment: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'searchAssignment',fieldName:'searchAssignment',position:10,isVisible:true,size:150,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsNotes: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'notes',fieldName:'notes',position:11,isVisible:true,size:200,viewFieldGroupName:'general'}}),
compensationExpectationRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'createdAt',fieldName:'createdAt',position:12,isVisible:true,size:150,viewFieldGroupName:'system'}}),
compensationExpectationRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({...args,objectName:'compensationExpectation',context:{viewName:'compensationExpectationRecordPageFields',viewFieldName:'createdBy',fieldName:'createdBy',position:13,isVisible:true,size:150,viewFieldGroupName:'system'}}),
});
