import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';
import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { type CreateStandardViewFieldArgs, createStandardViewFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardAnalyticsMetricSnapshotViewFields = ({ context, }: Omit<CreateStandardViewFieldArgs<'analyticsMetricSnapshot'>, 'context'>): Record<string, FlatViewField> => ({
  name: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'name', fieldName: 'name', position: 0, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  metric: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'metric', fieldName: 'metric', position: 1, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  periodStart: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'periodStart', fieldName: 'periodStart', position: 2, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  periodEnd: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'periodEnd', fieldName: 'periodEnd', position: 3, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  granularity: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'granularity', fieldName: 'granularity', position: 4, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  value: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'value', fieldName: 'value', position: 5, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  computationStatus: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'computationStatus', fieldName: 'computationStatus', position: 6, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  computedAt: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'computedAt', fieldName: 'computedAt', position: 7, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  createdAt: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'createdAt', fieldName: 'createdAt', position: 8, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
  createdBy: createStandardViewFieldFlatMetadata({ args: { objectName: 'analyticsMetricSnapshot' as AllStandardObjectName, context: { viewName: 'analyticsMetricSnapshotRecordPageFields', viewFieldName: 'createdBy', fieldName: 'createdBy', position: 9, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
});
