import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';
import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { type CreateStandardViewFieldArgs, createStandardViewFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardBoardCompositionProfileViewFields = ({ context, }: Omit<CreateStandardViewFieldArgs<'boardCompositionProfile'>, 'context'>): Record<string, FlatViewField> => ({
  name: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'name', fieldName: 'name', position: 0, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  status: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'status', fieldName: 'status', position: 1, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  targetBoardType: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'targetBoardType', fieldName: 'targetBoardType', position: 2, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  industryPreference: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'industryPreference', fieldName: 'industryPreference', position: 3, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  currentSize: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'currentSize', fieldName: 'currentSize', position: 4, isVisible: true, size: 100, viewFieldGroupName: 'general', }, }, context, }),
  targetSize: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'targetSize', fieldName: 'targetSize', position: 5, isVisible: true, size: 100, viewFieldGroupName: 'general', }, }, context, }),
  notes: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'notes', fieldName: 'notes', position: 6, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  searchAssignment: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'searchAssignment', fieldName: 'searchAssignment', position: 7, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  createdAt: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'createdAt', fieldName: 'createdAt', position: 8, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
  createdBy: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCompositionProfile' as AllStandardObjectName, context: { viewName: 'boardCompositionProfileRecordPageFields', viewFieldName: 'createdBy', fieldName: 'createdBy', position: 9, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
});
