import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { createStandardViewFieldFlatMetadata, type CreateStandardViewFieldArgs } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardSearchInterviewViewFields = (args: Omit<CreateStandardViewFieldArgs<'searchInterview'>, 'context'>): Record<string, FlatViewField> => ({
searchInterviewRecordPageFieldsName: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'name',fieldName:'name',position:0,isVisible:true,size:200,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsInterviewType: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'interviewType',fieldName:'interviewType',position:1,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'status',fieldName:'status',position:2,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsScheduledDate: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'scheduledDate',fieldName:'scheduledDate',position:3,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsScheduledEndDate: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'scheduledEndDate',fieldName:'scheduledEndDate',position:4,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsDuration: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'duration',fieldName:'duration',position:5,isVisible:true,size:100,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsLocation: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'location',fieldName:'location',position:6,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsNotes: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'notes',fieldName:'notes',position:7,isVisible:true,size:200,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsOutcome: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'outcome',fieldName:'outcome',position:8,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsInternalNotes: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'internalNotes',fieldName:'internalNotes',position:9,isVisible:true,size:200,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsInterviewers: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'interviewers',fieldName:'interviewers',position:10,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsSearchAssignment: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'searchAssignment',fieldName:'searchAssignment',position:11,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsSearchCandidacy: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'searchCandidacy',fieldName:'searchCandidacy',position:12,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsClientFeedbacks: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'clientFeedbacks',fieldName:'clientFeedbacks',position:13,isVisible:true,size:150,viewFieldGroupName:'general'}}),
searchInterviewRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'createdAt',fieldName:'createdAt',position:14,isVisible:true,size:150,viewFieldGroupName:'system'}}),
searchInterviewRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({...args,objectName:'searchInterview',context:{viewName:'searchInterviewRecordPageFields',viewFieldName:'createdBy',fieldName:'createdBy',position:15,isVisible:true,size:150,viewFieldGroupName:'system'}}),
});
