import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { createStandardViewFieldFlatMetadata, type CreateStandardViewFieldArgs } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardReferenceCheckViewFields = (args: Omit<CreateStandardViewFieldArgs<'referenceCheck'>, 'context'>): Record<string, FlatViewField> => ({
referenceCheckRecordPageFieldsName: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'name',fieldName:'name',position:0,isVisible:true,size:200,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'status',fieldName:'status',position:1,isVisible:true,size:150,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsReferenceName: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'referenceName',fieldName:'referenceName',position:2,isVisible:true,size:200,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsReferenceTitle: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'referenceTitle',fieldName:'referenceTitle',position:3,isVisible:true,size:150,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsReferenceOrganization: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'referenceOrganization',fieldName:'referenceOrganization',position:4,isVisible:true,size:150,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsRelationshipType: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'relationshipType',fieldName:'relationshipType',position:5,isVisible:true,size:150,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsFindings: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'findings',fieldName:'findings',position:6,isVisible:true,size:200,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsSearchCandidacy: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'searchCandidacy',fieldName:'searchCandidacy',position:7,isVisible:true,size:150,viewFieldGroupName:'general'}}),
referenceCheckRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'createdAt',fieldName:'createdAt',position:8,isVisible:true,size:150,viewFieldGroupName:'system'}}),
referenceCheckRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'createdBy',fieldName:'createdBy',position:9,isVisible:true,size:150,viewFieldGroupName:'system'}}),
referenceCheckRecordPageFieldsVerifiedAt: createStandardViewFieldFlatMetadata({...args,objectName:'referenceCheck',context:{viewName:'referenceCheckRecordPageFields',viewFieldName:'verifiedAt',fieldName:'verifiedAt',position:10,isVisible:true,size:150,viewFieldGroupName:'general'}}),
});
