import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';
import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { type CreateStandardViewFieldArgs, createStandardViewFieldFlatMetadata, } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardBoardCommitmentReviewViewFields = ({ context, }: Omit<CreateStandardViewFieldArgs<'boardCommitmentReview'>, 'context'>): Record<string, FlatViewField> => ({
  name: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'name', fieldName: 'name', position: 0, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  status: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'status', fieldName: 'status', position: 1, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  reviewDate: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'reviewDate', fieldName: 'reviewDate', position: 2, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  currentBoardCount: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'currentBoardCount', fieldName: 'currentBoardCount', position: 3, isVisible: true, size: 100, viewFieldGroupName: 'general', }, }, context, }),
  currentChairCount: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'currentChairCount', fieldName: 'currentChairCount', position: 4, isVisible: true, size: 100, viewFieldGroupName: 'general', }, }, context, }),
  totalCommitmentHoursEstimate: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'totalCommitmentHoursEstimate', fieldName: 'totalCommitmentHoursEstimate', position: 5, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  findings: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'findings', fieldName: 'findings', position: 6, isVisible: true, size: 200, viewFieldGroupName: 'general', }, }, context, }),
  searchCandidacyId: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'searchCandidacyId', fieldName: 'searchCandidacyId', position: 7, isVisible: true, size: 150, viewFieldGroupName: 'general', }, }, context, }),
  createdAt: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'createdAt', fieldName: 'createdAt', position: 8, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
  createdBy: createStandardViewFieldFlatMetadata({ args: { objectName: 'boardCommitmentReview' as AllStandardObjectName, context: { viewName: 'boardCommitmentReviewRecordPageFields', viewFieldName: 'createdBy', fieldName: 'createdBy', position: 9, isVisible: true, size: 150, viewFieldGroupName: 'system', }, }, context, }),
});
