import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import { createStandardViewFieldFlatMetadata, type CreateStandardViewFieldArgs } from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardGuaranteeCaseViewFields = (args: Omit<CreateStandardViewFieldArgs<'guaranteeCase'>, 'context'>): Record<string, FlatViewField> => ({
guaranteeCaseRecordPageFieldsName: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'name',fieldName:'name',position:0,isVisible:true,size:200,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'status',fieldName:'status',position:1,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsActiveFrom: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'activeFrom',fieldName:'activeFrom',position:2,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsActiveUntil: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'activeUntil',fieldName:'activeUntil',position:3,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsGuaranteeType: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'guaranteeType',fieldName:'guaranteeType',position:4,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsClaimFiledAt: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'claimFiledAt',fieldName:'claimFiledAt',position:5,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsClaimAmount: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'claimAmount',fieldName:'claimAmount',position:6,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsPlacement: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'placement',fieldName:'placement',position:7,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsSearchAssignment: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'searchAssignment',fieldName:'searchAssignment',position:8,isVisible:true,size:150,viewFieldGroupName:'general'}}),
guaranteeCaseRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'createdAt',fieldName:'createdAt',position:9,isVisible:true,size:150,viewFieldGroupName:'system'}}),
guaranteeCaseRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({...args,objectName:'guaranteeCase',context:{viewName:'guaranteeCaseRecordPageFields',viewFieldName:'createdBy',fieldName:'createdBy',position:10,isVisible:true,size:150,viewFieldGroupName:'system'}}),
});
